// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aihues/catalog/v1/service.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListToolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Q     string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"` // optional keyword（匹配 name/description）
	// 每页数据量；默认 10，最大 20
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 分页 token；第一页不传，后续传上一页返回的 next_page_token
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// 不传或 ITEM_CATEGORY_UNSPECIFIED 表示不过滤
	Category      ItemCategory `protobuf:"varint,4,opt,name=category,proto3,enum=aihues.catalog.v1.ItemCategory" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsRequest) Reset() {
	*x = ListToolsRequest{}
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsRequest) ProtoMessage() {}

func (x *ListToolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsRequest.ProtoReflect.Descriptor instead.
func (*ListToolsRequest) Descriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListToolsRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *ListToolsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListToolsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListToolsRequest) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

type ListToolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tools         []*Tool                `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListToolsResponse) Reset() {
	*x = ListToolsResponse{}
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListToolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolsResponse) ProtoMessage() {}

func (x *ListToolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolsResponse.ProtoReflect.Descriptor instead.
func (*ListToolsResponse) Descriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListToolsResponse) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *ListToolsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListGamesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 每页数据量；默认 10，最大 20
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 分页 token；第一页不传，后续传上一页返回的 next_page_token
	PageToken     string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesRequest) Reset() {
	*x = ListGamesRequest{}
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesRequest) ProtoMessage() {}

func (x *ListGamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesRequest.ProtoReflect.Descriptor instead.
func (*ListGamesRequest) Descriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListGamesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListGamesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListGamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*Game                `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGamesResponse) Reset() {
	*x = ListGamesResponse{}
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGamesResponse) ProtoMessage() {}

func (x *ListGamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aihues_catalog_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGamesResponse.ProtoReflect.Descriptor instead.
func (*ListGamesResponse) Descriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListGamesResponse) GetGames() []*Game {
	if x != nil {
		return x.Games
	}
	return nil
}

func (x *ListGamesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_aihues_catalog_v1_service_proto protoreflect.FileDescriptor

const file_aihues_catalog_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1faihues/catalog/v1/service.proto\x12\x11aihues.catalog.v1\x1a\x1daihues/catalog/v1/types.proto\"\x99\x01\n" +
	"\x10ListToolsRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12;\n" +
	"\bcategory\x18\x04 \x01(\x0e2\x1f.aihues.catalog.v1.ItemCategoryR\bcategory\"j\n" +
	"\x11ListToolsResponse\x12-\n" +
	"\x05tools\x18\x01 \x03(\v2\x17.aihues.catalog.v1.ToolR\x05tools\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x10ListGamesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"j\n" +
	"\x11ListGamesResponse\x12-\n" +
	"\x05games\x18\x01 \x03(\v2\x17.aihues.catalog.v1.GameR\x05games\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xc0\x01\n" +
	"\x0eCatalogService\x12V\n" +
	"\tListTools\x12#.aihues.catalog.v1.ListToolsRequest\x1a$.aihues.catalog.v1.ListToolsResponse\x12V\n" +
	"\tListGames\x12#.aihues.catalog.v1.ListGamesRequest\x1a$.aihues.catalog.v1.ListGamesResponseBJZHgithub.com/aihues/aiushtha/packages/proto-go/aihues/catalog/v1;catalogv1b\x06proto3"

var (
	file_aihues_catalog_v1_service_proto_rawDescOnce sync.Once
	file_aihues_catalog_v1_service_proto_rawDescData []byte
)

func file_aihues_catalog_v1_service_proto_rawDescGZIP() []byte {
	file_aihues_catalog_v1_service_proto_rawDescOnce.Do(func() {
		file_aihues_catalog_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aihues_catalog_v1_service_proto_rawDesc), len(file_aihues_catalog_v1_service_proto_rawDesc)))
	})
	return file_aihues_catalog_v1_service_proto_rawDescData
}

var file_aihues_catalog_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aihues_catalog_v1_service_proto_goTypes = []any{
	(*ListToolsRequest)(nil),  // 0: aihues.catalog.v1.ListToolsRequest
	(*ListToolsResponse)(nil), // 1: aihues.catalog.v1.ListToolsResponse
	(*ListGamesRequest)(nil),  // 2: aihues.catalog.v1.ListGamesRequest
	(*ListGamesResponse)(nil), // 3: aihues.catalog.v1.ListGamesResponse
	(ItemCategory)(0),         // 4: aihues.catalog.v1.ItemCategory
	(*Tool)(nil),              // 5: aihues.catalog.v1.Tool
	(*Game)(nil),              // 6: aihues.catalog.v1.Game
}
var file_aihues_catalog_v1_service_proto_depIdxs = []int32{
	4, // 0: aihues.catalog.v1.ListToolsRequest.category:type_name -> aihues.catalog.v1.ItemCategory
	5, // 1: aihues.catalog.v1.ListToolsResponse.tools:type_name -> aihues.catalog.v1.Tool
	6, // 2: aihues.catalog.v1.ListGamesResponse.games:type_name -> aihues.catalog.v1.Game
	0, // 3: aihues.catalog.v1.CatalogService.ListTools:input_type -> aihues.catalog.v1.ListToolsRequest
	2, // 4: aihues.catalog.v1.CatalogService.ListGames:input_type -> aihues.catalog.v1.ListGamesRequest
	1, // 5: aihues.catalog.v1.CatalogService.ListTools:output_type -> aihues.catalog.v1.ListToolsResponse
	3, // 6: aihues.catalog.v1.CatalogService.ListGames:output_type -> aihues.catalog.v1.ListGamesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aihues_catalog_v1_service_proto_init() }
func file_aihues_catalog_v1_service_proto_init() {
	if File_aihues_catalog_v1_service_proto != nil {
		return
	}
	file_aihues_catalog_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aihues_catalog_v1_service_proto_rawDesc), len(file_aihues_catalog_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aihues_catalog_v1_service_proto_goTypes,
		DependencyIndexes: file_aihues_catalog_v1_service_proto_depIdxs,
		MessageInfos:      file_aihues_catalog_v1_service_proto_msgTypes,
	}.Build()
	File_aihues_catalog_v1_service_proto = out.File
	file_aihues_catalog_v1_service_proto_goTypes = nil
	file_aihues_catalog_v1_service_proto_depIdxs = nil
}
