// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aihues/catalog/v1/types.proto

package catalogv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 条目类型（多态目录表的行类型判别符；仅用于内部存储，不暴露在 Tool / Game 消息上）
type ItemKind int32

const (
	ItemKind_ITEM_KIND_UNSPECIFIED ItemKind = 0
	ItemKind_ITEM_KIND_TOOL        ItemKind = 1
	ItemKind_ITEM_KIND_GAME        ItemKind = 2
)

// Enum value maps for ItemKind.
var (
	ItemKind_name = map[int32]string{
		0: "ITEM_KIND_UNSPECIFIED",
		1: "ITEM_KIND_TOOL",
		2: "ITEM_KIND_GAME",
	}
	ItemKind_value = map[string]int32{
		"ITEM_KIND_UNSPECIFIED": 0,
		"ITEM_KIND_TOOL":        1,
		"ITEM_KIND_GAME":        2,
	}
)

func (x ItemKind) Enum() *ItemKind {
	p := new(ItemKind)
	*p = x
	return p
}

func (x ItemKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemKind) Descriptor() protoreflect.EnumDescriptor {
	return file_aihues_catalog_v1_types_proto_enumTypes[0].Descriptor()
}

func (ItemKind) Type() protoreflect.EnumType {
	return &file_aihues_catalog_v1_types_proto_enumTypes[0]
}

func (x ItemKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemKind.Descriptor instead.
func (ItemKind) EnumDescriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_types_proto_rawDescGZIP(), []int{0}
}

// 条目状态
type ItemStatus int32

const (
	ItemStatus_ITEM_STATUS_UNSPECIFIED ItemStatus = 0
	ItemStatus_ITEM_STATUS_DRAFT       ItemStatus = 1
	ItemStatus_ITEM_STATUS_PUBLISHED   ItemStatus = 2
	ItemStatus_ITEM_STATUS_ARCHIVED    ItemStatus = 3
)

// Enum value maps for ItemStatus.
var (
	ItemStatus_name = map[int32]string{
		0: "ITEM_STATUS_UNSPECIFIED",
		1: "ITEM_STATUS_DRAFT",
		2: "ITEM_STATUS_PUBLISHED",
		3: "ITEM_STATUS_ARCHIVED",
	}
	ItemStatus_value = map[string]int32{
		"ITEM_STATUS_UNSPECIFIED": 0,
		"ITEM_STATUS_DRAFT":       1,
		"ITEM_STATUS_PUBLISHED":   2,
		"ITEM_STATUS_ARCHIVED":    3,
	}
)

func (x ItemStatus) Enum() *ItemStatus {
	p := new(ItemStatus)
	*p = x
	return p
}

func (x ItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_aihues_catalog_v1_types_proto_enumTypes[1].Descriptor()
}

func (ItemStatus) Type() protoreflect.EnumType {
	return &file_aihues_catalog_v1_types_proto_enumTypes[1]
}

func (x ItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemStatus.Descriptor instead.
func (ItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_types_proto_rawDescGZIP(), []int{1}
}

// 条目分类（tool / game 通用；目前枚举值仅覆盖 tool，未来 game 分类可在此扩展）
type ItemCategory int32

const (
	ItemCategory_ITEM_CATEGORY_UNSPECIFIED ItemCategory = 0
	ItemCategory_ITEM_CATEGORY_DEVELOPER   ItemCategory = 1
	ItemCategory_ITEM_CATEGORY_UTILITY     ItemCategory = 2
	ItemCategory_ITEM_CATEGORY_AI_WRITING  ItemCategory = 3
	ItemCategory_ITEM_CATEGORY_IMAGE       ItemCategory = 4
)

// Enum value maps for ItemCategory.
var (
	ItemCategory_name = map[int32]string{
		0: "ITEM_CATEGORY_UNSPECIFIED",
		1: "ITEM_CATEGORY_DEVELOPER",
		2: "ITEM_CATEGORY_UTILITY",
		3: "ITEM_CATEGORY_AI_WRITING",
		4: "ITEM_CATEGORY_IMAGE",
	}
	ItemCategory_value = map[string]int32{
		"ITEM_CATEGORY_UNSPECIFIED": 0,
		"ITEM_CATEGORY_DEVELOPER":   1,
		"ITEM_CATEGORY_UTILITY":     2,
		"ITEM_CATEGORY_AI_WRITING":  3,
		"ITEM_CATEGORY_IMAGE":       4,
	}
)

func (x ItemCategory) Enum() *ItemCategory {
	p := new(ItemCategory)
	*p = x
	return p
}

func (x ItemCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_aihues_catalog_v1_types_proto_enumTypes[2].Descriptor()
}

func (ItemCategory) Type() protoreflect.EnumType {
	return &file_aihues_catalog_v1_types_proto_enumTypes[2]
}

func (x ItemCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemCategory.Descriptor instead.
func (ItemCategory) EnumDescriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_types_proto_rawDescGZIP(), []int{2}
}

// 价格标签
type PriceTag int32

const (
	PriceTag_PRICE_TAG_UNSPECIFIED PriceTag = 0
	PriceTag_PRICE_TAG_FREE        PriceTag = 1
	PriceTag_PRICE_TAG_FREEMIUM    PriceTag = 2
	PriceTag_PRICE_TAG_PAID        PriceTag = 3
)

// Enum value maps for PriceTag.
var (
	PriceTag_name = map[int32]string{
		0: "PRICE_TAG_UNSPECIFIED",
		1: "PRICE_TAG_FREE",
		2: "PRICE_TAG_FREEMIUM",
		3: "PRICE_TAG_PAID",
	}
	PriceTag_value = map[string]int32{
		"PRICE_TAG_UNSPECIFIED": 0,
		"PRICE_TAG_FREE":        1,
		"PRICE_TAG_FREEMIUM":    2,
		"PRICE_TAG_PAID":        3,
	}
)

func (x PriceTag) Enum() *PriceTag {
	p := new(PriceTag)
	*p = x
	return p
}

func (x PriceTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceTag) Descriptor() protoreflect.EnumDescriptor {
	return file_aihues_catalog_v1_types_proto_enumTypes[3].Descriptor()
}

func (PriceTag) Type() protoreflect.EnumType {
	return &file_aihues_catalog_v1_types_proto_enumTypes[3]
}

func (x PriceTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceTag.Descriptor instead.
func (PriceTag) EnumDescriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_types_proto_rawDescGZIP(), []int{3}
}

// 工具元数据
type Tool struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug        string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Icon        string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Name        string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Category    ItemCategory           `protobuf:"varint,6,opt,name=category,proto3,enum=aihues.catalog.v1.ItemCategory" json:"category,omitempty"`
	Status      ItemStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=aihues.catalog.v1.ItemStatus" json:"status,omitempty"`
	SortOrder   int32                  `protobuf:"varint,8,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// ── 新增字段 ──
	PriceTag      PriceTag `protobuf:"varint,11,opt,name=price_tag,json=priceTag,proto3,enum=aihues.catalog.v1.PriceTag" json:"price_tag,omitempty"` // 价格标签
	ExternalUrl   string   `protobuf:"bytes,12,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`                         // 外链地址
	Tags          []string `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`                                                          // 关键词标签
	CreditCost    int32    `protobuf:"varint,14,opt,name=credit_cost,json=creditCost,proto3" json:"credit_cost,omitempty"`                           // 积分消耗（0 = 免费）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_aihues_catalog_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_aihues_catalog_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Tool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tool) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Tool) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Tool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tool) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tool) GetCategory() ItemCategory {
	if x != nil {
		return x.Category
	}
	return ItemCategory_ITEM_CATEGORY_UNSPECIFIED
}

func (x *Tool) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *Tool) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Tool) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Tool) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Tool) GetPriceTag() PriceTag {
	if x != nil {
		return x.PriceTag
	}
	return PriceTag_PRICE_TAG_UNSPECIFIED
}

func (x *Tool) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *Tool) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tool) GetCreditCost() int32 {
	if x != nil {
		return x.CreditCost
	}
	return 0
}

// 游戏元数据
type Game struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug        string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Icon        string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	Name        string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Status      ItemStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=aihues.catalog.v1.ItemStatus" json:"status,omitempty"`
	SortOrder   int32                  `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CreateTime  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// ── 新增字段 ──
	PriceTag      PriceTag `protobuf:"varint,10,opt,name=price_tag,json=priceTag,proto3,enum=aihues.catalog.v1.PriceTag" json:"price_tag,omitempty"` // 价格标签
	ExternalUrl   string   `protobuf:"bytes,11,opt,name=external_url,json=externalUrl,proto3" json:"external_url,omitempty"`                         // 外链地址
	Tags          []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`                                                          // 关键词标签
	CreditCost    int32    `protobuf:"varint,13,opt,name=credit_cost,json=creditCost,proto3" json:"credit_cost,omitempty"`                           // 积分消耗
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_aihues_catalog_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_aihues_catalog_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_aihues_catalog_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Game) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Game) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Game) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Game) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Game) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Game) GetStatus() ItemStatus {
	if x != nil {
		return x.Status
	}
	return ItemStatus_ITEM_STATUS_UNSPECIFIED
}

func (x *Game) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Game) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Game) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Game) GetPriceTag() PriceTag {
	if x != nil {
		return x.PriceTag
	}
	return PriceTag_PRICE_TAG_UNSPECIFIED
}

func (x *Game) GetExternalUrl() string {
	if x != nil {
		return x.ExternalUrl
	}
	return ""
}

func (x *Game) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Game) GetCreditCost() int32 {
	if x != nil {
		return x.CreditCost
	}
	return 0
}

var File_aihues_catalog_v1_types_proto protoreflect.FileDescriptor

const file_aihues_catalog_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1daihues/catalog/v1/types.proto\x12\x11aihues.catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x04\n" +
	"\x04Tool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12;\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x1f.aihues.catalog.v1.ItemCategoryR\bcategory\x125\n" +
	"\x06status\x18\a \x01(\x0e2\x1d.aihues.catalog.v1.ItemStatusR\x06status\x12\x1d\n" +
	"\n" +
	"sort_order\x18\b \x01(\x05R\tsortOrder\x12;\n" +
	"\vcreate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x128\n" +
	"\tprice_tag\x18\v \x01(\x0e2\x1b.aihues.catalog.v1.PriceTagR\bpriceTag\x12!\n" +
	"\fexternal_url\x18\f \x01(\tR\vexternalUrl\x12\x12\n" +
	"\x04tags\x18\r \x03(\tR\x04tags\x12\x1f\n" +
	"\vcredit_cost\x18\x0e \x01(\x05R\n" +
	"creditCost\"\xd6\x03\n" +
	"\x04Game\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x125\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1d.aihues.catalog.v1.ItemStatusR\x06status\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x128\n" +
	"\tprice_tag\x18\n" +
	" \x01(\x0e2\x1b.aihues.catalog.v1.PriceTagR\bpriceTag\x12!\n" +
	"\fexternal_url\x18\v \x01(\tR\vexternalUrl\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12\x1f\n" +
	"\vcredit_cost\x18\r \x01(\x05R\n" +
	"creditCost*M\n" +
	"\bItemKind\x12\x19\n" +
	"\x15ITEM_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eITEM_KIND_TOOL\x10\x01\x12\x12\n" +
	"\x0eITEM_KIND_GAME\x10\x02*u\n" +
	"\n" +
	"ItemStatus\x12\x1b\n" +
	"\x17ITEM_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ITEM_STATUS_DRAFT\x10\x01\x12\x19\n" +
	"\x15ITEM_STATUS_PUBLISHED\x10\x02\x12\x18\n" +
	"\x14ITEM_STATUS_ARCHIVED\x10\x03*\x9c\x01\n" +
	"\fItemCategory\x12\x1d\n" +
	"\x19ITEM_CATEGORY_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17ITEM_CATEGORY_DEVELOPER\x10\x01\x12\x19\n" +
	"\x15ITEM_CATEGORY_UTILITY\x10\x02\x12\x1c\n" +
	"\x18ITEM_CATEGORY_AI_WRITING\x10\x03\x12\x17\n" +
	"\x13ITEM_CATEGORY_IMAGE\x10\x04*e\n" +
	"\bPriceTag\x12\x19\n" +
	"\x15PRICE_TAG_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePRICE_TAG_FREE\x10\x01\x12\x16\n" +
	"\x12PRICE_TAG_FREEMIUM\x10\x02\x12\x12\n" +
	"\x0ePRICE_TAG_PAID\x10\x03BJZHgithub.com/aihues/aiushtha/packages/proto-go/aihues/catalog/v1;catalogv1b\x06proto3"

var (
	file_aihues_catalog_v1_types_proto_rawDescOnce sync.Once
	file_aihues_catalog_v1_types_proto_rawDescData []byte
)

func file_aihues_catalog_v1_types_proto_rawDescGZIP() []byte {
	file_aihues_catalog_v1_types_proto_rawDescOnce.Do(func() {
		file_aihues_catalog_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aihues_catalog_v1_types_proto_rawDesc), len(file_aihues_catalog_v1_types_proto_rawDesc)))
	})
	return file_aihues_catalog_v1_types_proto_rawDescData
}

var file_aihues_catalog_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_aihues_catalog_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aihues_catalog_v1_types_proto_goTypes = []any{
	(ItemKind)(0),                 // 0: aihues.catalog.v1.ItemKind
	(ItemStatus)(0),               // 1: aihues.catalog.v1.ItemStatus
	(ItemCategory)(0),             // 2: aihues.catalog.v1.ItemCategory
	(PriceTag)(0),                 // 3: aihues.catalog.v1.PriceTag
	(*Tool)(nil),                  // 4: aihues.catalog.v1.Tool
	(*Game)(nil),                  // 5: aihues.catalog.v1.Game
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_aihues_catalog_v1_types_proto_depIdxs = []int32{
	2, // 0: aihues.catalog.v1.Tool.category:type_name -> aihues.catalog.v1.ItemCategory
	1, // 1: aihues.catalog.v1.Tool.status:type_name -> aihues.catalog.v1.ItemStatus
	6, // 2: aihues.catalog.v1.Tool.create_time:type_name -> google.protobuf.Timestamp
	6, // 3: aihues.catalog.v1.Tool.update_time:type_name -> google.protobuf.Timestamp
	3, // 4: aihues.catalog.v1.Tool.price_tag:type_name -> aihues.catalog.v1.PriceTag
	1, // 5: aihues.catalog.v1.Game.status:type_name -> aihues.catalog.v1.ItemStatus
	6, // 6: aihues.catalog.v1.Game.create_time:type_name -> google.protobuf.Timestamp
	6, // 7: aihues.catalog.v1.Game.update_time:type_name -> google.protobuf.Timestamp
	3, // 8: aihues.catalog.v1.Game.price_tag:type_name -> aihues.catalog.v1.PriceTag
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_aihues_catalog_v1_types_proto_init() }
func file_aihues_catalog_v1_types_proto_init() {
	if File_aihues_catalog_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aihues_catalog_v1_types_proto_rawDesc), len(file_aihues_catalog_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aihues_catalog_v1_types_proto_goTypes,
		DependencyIndexes: file_aihues_catalog_v1_types_proto_depIdxs,
		EnumInfos:         file_aihues_catalog_v1_types_proto_enumTypes,
		MessageInfos:      file_aihues_catalog_v1_types_proto_msgTypes,
	}.Build()
	File_aihues_catalog_v1_types_proto = out.File
	file_aihues_catalog_v1_types_proto_goTypes = nil
	file_aihues_catalog_v1_types_proto_depIdxs = nil
}
