variables:
  GIT_DEPTH: "0"
  GIT_CLEAN_FLAGS: -ffdx
  MOON_COLOR: "2"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG

default:
  image: msai-cn-beijing.cr.volces.com/msai/devops/ci-base-node:v0.0.2
  tags:
    - kimi
  before_script:
    - export PATH=$PWD/node_modules/.bin:$PATH
    - pnpm install --frozen-lockfile

stages:
  - test
  - build

lint:
  stage: test
  script:
    - pnpm check
    - echo "✅ Lint successful"

Build Web Image:
  stage: build
  script:
    - moon run papers-web:container
    - echo "✅ Build web image successful"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

Build API Image:
  stage: build
  script:
    - moon run papers-api:container
    - echo "✅ Build api image successful"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
