variables:
  # Disable shallow clone to suppress git error in moon command.
  # Otherwise you may encounter git failue like:
  # fatal: ambiguous argument 'main': unknown revision or path not in the working tree.
  # More information:
  # - https://github.com/moonrepo/moon/issues/1038
  # - https://docs.gitlab.com/ee/ci/large_repositories/#shallow-cloning
  GIT_DEPTH: "0"
  # Clean untracked files between jobs to avoid stale node_modules/.pnpm links.
  GIT_CLEAN_FLAGS: -ffdx
  # Color output
  MOON_COLOR: "2"

# To avoid duplicate pipelines when using job rules
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

default:
  image: msai-cn-beijing.cr.volces.com/msai/devops/ci-base:latest
  before_script:
    - export PATH=$PWD/node_modules/.bin:$PATH
    - npm config set registry https://registry.npmmirror.com
    - pnpm install --frozen-lockfile
    - env
  tags:
    - kimi

stages:
  - test
  - build
  - security-test

sast-scan-js:
  stage: security-test
  tags:
    - docker
  variables:
    CORAX_RULE: 'Corax 推荐-JavaScript'
    PROJECT_NAME: '${CI_PROJECT_NAME}-js'
  image: msai-cn-beijing.cr.volces.com/security/sast:latest
  before_script: []
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
  script:
    - TIMESTAMP=$(date +%Y-%m-%d-%H:%M:%S)
    - corax run --init -p "${PROJECT_NAME}" -t "${CI_COMMIT_SHORT_SHA}${CI_PIPELINE_ID}${TIMESTAMP}" -r "${CORAX_RULE}" --token "$CORAX_TOKEN" --server-path "$CORAX_HOST"

lint:
  stage: test
  script:
    - pnpm moon run aihues-web:lint aihues-web:format-check aihues-web:typecheck
    - echo "✅ Lint successful"

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -f apps/aihues-web/Dockerfile -t msai-cn-beijing.cr.volces.com/msai/aihues-web:$CI_COMMIT_SHORT_SHA .
    - docker push msai-cn-beijing.cr.volces.com/msai/aihues-web:$CI_COMMIT_SHORT_SHA
    - echo "✅ Build image successful"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "feature/design-refresh"
      when: on_success
