/* ── AIHues bilingual dictionary ──
   Flat keys, dot-separated namespaces.
   Usage: t('hero.title') → 'Find your AI vibe'
*/

export type Locale = 'en' | 'zh';

export const dict: Record<Locale, Record<string, string>> = {
  en: {
    // nav
    'nav.home': 'Home',
    'nav.tools': 'Tools',
    'nav.games': 'Games',
    'nav.blog': 'Blog',
    'nav.wishlist': 'Wishlist',
    'nav.ranking': 'Ranking',
    'nav.discover': 'Discover',
    'nav.login': 'Login',

    // hero
    'hero.title': 'Find your',
    'hero.aiVibe': 'AI vibe',
    'hero.subtitle':
      '57+ AI tools, mini games & utilities that just work. Tell us what you need.',
    'hero.searchPlaceholder': "e.g. 'parse JWT'... (Press / to focus)",
    'hero.askAI': 'Ask AI',

    // categories
    'categories.title': 'Browse by category',
    'categories.seeAll': 'See all tools →',
    'cat.utility': 'Utility',
    'cat.developer': 'Developer',
    'cat.aiWriting': 'AI Writing',
    'cat.games': 'Games',
    'cat.utilityDesc': 'Word Count, Diff, Fullwidth, Readability, Humanize',
    'cat.developerDesc': 'JWT, JSON, Regex, Base64, UUID, QR Code, SHA256',
    'cat.aiWritingDesc': 'X Post, Blog Outline, SEO Title, Newsletter, PR Desc',
    'cat.gamesDesc': 'Daily Fortune, Slots, Hoops — earn Credits',

    // stats
    'stats.aiTools': 'AI Tools',
    'stats.devTools': 'Dev Tools',
    'stats.games': 'Games',
    'stats.freeCredits': 'Free Credits',
    'stats.dayStreak': 'Day Streak',

    // sections
    'section.devTools': 'Developer Tools',
    'section.newThisWeek': 'New This Week',
    'section.tools': 'tools',
    'section.allTools': 'All tools →',
    'section.writingTools': 'Writing Tools',
    'section.gameCenter': 'Game Center',
    'section.creditBalance': 'Your Credit Balance',
    'section.viewAll': 'View all →',
    'section.popularTools': 'Popular Tools',
    'section.dualEngine': 'Tools + Games Dual Engine',
    'section.dualEngineDesc':
      'Use tools, then play a game to relax. 57 tools + 3 games = complete platform.',
    'section.browseAll': 'Browse All Tools →',
    'section.wishlistTitle': "Can't find what you need?",
    'section.wishlistDesc': 'Submit your idea. Top requests get built first.',
    'section.submitIdea': 'Submit Your Idea →',

    // games
    'game.draw': 'Draw →',
    'game.spin': 'Spin →',
    'game.play': 'Play →',
    'game.dailyLuckDesc': 'Daily draw for wisdom & Credit rewards',
    'game.slotMachineDesc': '3 free spins daily, win big prizes',
    'game.basketballDesc': '60 seconds to score maximum points',
    'game.daily': 'DAILY',
    'game.popular': 'POPULAR',
    'game.skill': 'SKILL',

    // credit
    'credit.title': 'Credit Rules',
    'credit.initial': 'Initial Bonus',
    'credit.initialDesc': 'Start with 100 credits',
    'credit.playToEarn': 'Play to Earn',
    'credit.playToEarnDesc': '+5~100 credits per game',
    'credit.useTools': 'Use Tools',
    'credit.useToolsDesc': 'Spend credits on premium tools',
    'credit.dailyCheckin': 'Daily Check-in',
    'credit.dailyCheckinDesc': '+10 credits daily, streak bonus',
    'credit.howItWorks': 'How it works',
    'credit.yourCredits': 'Your Credits',
    'credit.perGame': 'Credits/Game',

    // sidebar
    'sidebar.allTools': 'All Tools',
    'sidebar.growth': 'Growth',
    'sidebar.devTools': 'Developer Tools',
    'sidebar.utilities': 'Utilities',
    'sidebar.aiProducts': 'AI Products',
    'sidebar.openSource': 'Open Source',
    'sidebar.design': 'Design',
    'sidebar.miniGames': 'Mini Games',

    // price filter
    'price.all': 'All',
    'price.free': 'Free',
    'price.freemium': 'Freemium',
    'price.paid': 'Paid',

    // tools
    'tool.wordCount.title': 'Word Counter',
    'tool.wordCount.desc': 'Real-time character, word, and line counting',
    'tool.wordCount.placeholder': 'Paste or type your text here...',
    'tool.wordCount.chars': 'Characters',
    'tool.wordCount.charsNoSpace': 'No Space',
    'tool.wordCount.words': 'Words',
    'tool.wordCount.lines': 'Lines',
    'tool.wordCount.paragraphs': 'Paragraphs',
    'tool.wordCount.readTime': 'Read Time',
    'tool.wordCount.clear': 'Clear',
    'tool.wordCount.copy': 'Copy',

    'tool.base64.title': 'Base64 Encoder / Decoder',
    'tool.base64.desc': 'Encode and decode Base64 strings instantly',
    'tool.base64.placeholder': 'Enter text to encode or Base64 to decode...',
    'tool.base64.encode': 'Encode',
    'tool.base64.decode': 'Decode',
    'tool.base64.result': 'Result',
    'tool.base64.urlSafe': 'URL-safe',

    'tool.urlEncode.title': 'URL Encoder / Decoder',
    'tool.urlEncode.desc': 'Encode and decode URL strings instantly',
    'tool.urlEncode.placeholder': 'Enter text to encode or URL-encoded text to decode...',
    'tool.urlEncode.encode': 'Encode',
    'tool.urlEncode.decode': 'Decode',
    'tool.urlEncode.result': 'Result',

    'tool.uuid.title': 'UUID Generator',
    'tool.uuid.desc': 'Generate random UUID v4 identifiers instantly',
    'tool.uuid.generate': 'Generate',
    'tool.uuid.generate5': 'Generate 5',
    'tool.uuid.generate10': 'Generate 10',
    'tool.uuid.history': 'History',
    'tool.uuid.copy': 'Copy',
    'tool.uuid.copyAll': 'Copy All',

    'tool.jwt.title': 'JWT Parser',
    'tool.jwt.desc': 'Decode and inspect JSON Web Tokens',
    'tool.jwt.placeholder': 'Paste JWT token here...',
    'tool.jwt.parse': 'Parse',
    'tool.jwt.header': 'Header',
    'tool.jwt.payload': 'Payload',
    'tool.jwt.signature': 'Signature',
    'tool.jwt.expired': 'Expired',
    'tool.jwt.valid': 'Valid',
    'tool.jwt.expiresAt': 'Expires at',

    'tool.json.title': 'JSON Formatter',
    'tool.json.desc': 'Format, validate, and minify JSON instantly',
    'tool.json.placeholder': 'Paste JSON here...',
    'tool.json.format': 'Format',
    'tool.json.minify': 'Minify',
    'tool.json.validate': 'Validate',
    'tool.json.result': 'Result',
    'tool.json.invalid': 'Invalid JSON',

    'tool.sha256.title': 'SHA-256 Hash',
    'tool.sha256.desc': 'Compute SHA-256 hash of any text',
    'tool.sha256.placeholder': 'Enter text to hash...',
    'tool.sha256.hash': 'Hash',
    'tool.sha256.result': 'Result',

    'tool.lorem.title': 'Lorem Ipsum Generator',
    'tool.lorem.desc': 'Generate placeholder text for your designs',
    'tool.lorem.paragraphs': 'Paragraphs',
    'tool.lorem.sentences': 'Sentences per paragraph',
    'tool.lorem.generate': 'Generate',
    'tool.lorem.copy': 'Copy',

    'tool.timestamp.title': 'Timestamp Converter',
    'tool.timestamp.desc': 'Convert between Unix timestamps and human-readable dates',
    'tool.timestamp.placeholder': 'Enter Unix timestamp or ISO date...',
    'tool.timestamp.convert': 'Convert',
    'tool.timestamp.local': 'Local Time',
    'tool.timestamp.utc': 'UTC',
    'tool.timestamp.unixSeconds': 'Unix Seconds',
    'tool.timestamp.unixMs': 'Unix Milliseconds',
    'tool.timestamp.relative': 'Relative',

    'tool.htmlEntity.title': 'HTML Entity Encoder / Decoder',
    'tool.htmlEntity.desc': 'Encode and decode HTML entities',
    'tool.htmlEntity.placeholder': 'Enter text or HTML entities...',
    'tool.htmlEntity.encode': 'Encode',
    'tool.htmlEntity.decode': 'Decode',
    'tool.htmlEntity.result': 'Result',

    'tool.fullwidth.title': 'Fullwidth Converter',
    'tool.fullwidth.desc': 'Convert between halfwidth and fullwidth characters',
    'tool.fullwidth.placeholder': 'Enter text to convert...',
    'tool.fullwidth.toFull': 'To Fullwidth',
    'tool.fullwidth.toHalf': 'To Halfwidth',
    'tool.fullwidth.result': 'Result',

    'tool.password.title': 'Password Generator',
    'tool.password.desc': 'Generate strong, secure passwords instantly',
    'tool.password.length': 'Length',
    'tool.password.uppercase': 'Uppercase (A-Z)',
    'tool.password.lowercase': 'Lowercase (a-z)',
    'tool.password.numbers': 'Numbers (0-9)',
    'tool.password.symbols': 'Symbols (!@#$...)',
    'tool.password.generate': 'Generate',
    'tool.password.copy': 'Copy',
    'tool.password.strength': 'Strength',

    'tool.regex.title': 'Regex Tester',
    'tool.regex.desc': 'Test regular expressions with live results',
    'tool.regex.pattern': 'Pattern',
    'tool.regex.patternPlaceholder': 'Enter regex pattern...',
    'tool.regex.flags': 'Flags',
    'tool.regex.testText': 'Test Text',
    'tool.regex.testTextPlaceholder': 'Enter text to test against...',
    'tool.regex.matches': 'Matches',
    'tool.regex.noMatches': 'No matches found',
    'tool.regex.groups': 'Groups',
    'tool.regex.error': 'Invalid regex',

    'tool.diff.title': 'Text Diff',
    'tool.diff.desc': 'Compare two texts line by line',
    'tool.diff.textA': 'Text A',
    'tool.diff.textB': 'Text B',
    'tool.diff.compare': 'Compare',
    'tool.diff.unchanged': 'Unchanged',
    'tool.diff.removed': 'Removed',
    'tool.diff.added': 'Added',
    'tool.diff.copy': 'Copy',

    'tool.csvJson.title': 'CSV / JSON Converter',
    'tool.csvJson.desc': 'Convert between CSV and JSON formats',
    'tool.csvJson.placeholder': 'Paste CSV or JSON here...',
    'tool.csvJson.convert': 'Convert',
    'tool.csvJson.result': 'Result',

    'tool.color.title': 'Color Converter',
    'tool.color.desc': 'Convert between HEX, RGB, and HSL color formats',
    'tool.color.placeholder': 'Enter HEX (e.g. #b45309) or rgb(...)...',
    'tool.color.convert': 'Convert',
    'tool.color.hex': 'HEX',
    'tool.color.rgb': 'RGB',
    'tool.color.hsl': 'HSL',
    'tool.color.preview': 'Preview',

    'tool.titleCase.title': 'Text Case Converter',
    'tool.titleCase.desc': 'Convert text between uppercase, lowercase, title case, and more',
    'tool.titleCase.placeholder': 'Enter text to convert...',
    'tool.titleCase.uppercase': 'UPPERCASE',
    'tool.titleCase.lowercase': 'lowercase',
    'tool.titleCase.titleCase': 'Title Case',
    'tool.titleCase.sentenceCase': 'Sentence case',
    'tool.titleCase.camelCase': 'camelCase',
    'tool.titleCase.snakeCase': 'snake_case',
    'tool.titleCase.kebabCase': 'kebab-case',
    'tool.titleCase.result': 'Result',

    'tool.gitCommit.title': 'Git Commit Message Generator',
    'tool.gitCommit.desc': 'Generate Conventional Commits formatted messages',
    'tool.gitCommit.type': 'Type',
    'tool.gitCommit.scope': 'Scope (optional)',
    'tool.gitCommit.description': 'Description',
    'tool.gitCommit.body': 'Body (optional)',
    'tool.gitCommit.footer': 'Footer (optional)',
    'tool.gitCommit.generate': 'Generate',
    'tool.gitCommit.result': 'Commit Message',
    'tool.gitCommit.copy': 'Copy',

    'gitCommit.feat': 'feat: A new feature',
    'gitCommit.fix': 'fix: A bug fix',
    'gitCommit.docs': 'docs: Documentation only changes',
    'gitCommit.style': 'style: Code style changes',
    'gitCommit.refactor': 'refactor: Code refactoring',
    'gitCommit.perf': 'perf: Performance improvements',
    'gitCommit.test': 'test: Adding or updating tests',
    'gitCommit.chore': 'chore: Build/process changes',

    'tool.readability.title': 'Readability Score',
    'tool.readability.desc': 'Analyze text readability with Flesch-Kincaid metrics',
    'tool.readability.placeholder': 'Paste text to analyze...',
    'tool.readability.analyze': 'Analyze',
    'tool.readability.words': 'Words',
    'tool.readability.sentences': 'Sentences',
    'tool.readability.avgSentenceLength': 'Avg Sentence Length',
    'tool.readability.syllables': 'Syllables',
    'tool.readability.fleschEase': 'Flesch Reading Ease',
    'tool.readability.fleschGrade': 'Flesch-Kincaid Grade',
    'tool.readability.rating': 'Rating',
    'tool.readability.veryEasy': 'Very Easy',
    'tool.readability.easy': 'Easy',
    'tool.readability.fairlyEasy': 'Fairly Easy',
    'tool.readability.standard': 'Standard',
    'tool.readability.fairlyDifficult': 'Fairly Difficult',
    'tool.readability.difficult': 'Difficult',
    'tool.readability.veryDifficult': 'Very Difficult',

    'tool.pomodoro.title': 'Pomodoro Timer',
    'tool.pomodoro.desc': 'Stay focused with the 25-minute technique',
    'tool.pomodoro.start': 'Start',
    'tool.pomodoro.pause': 'Pause',
    'tool.pomodoro.reset': 'Reset',
    'tool.pomodoro.minutes': 'minutes',
    'tool.pomodoro.done': 'Time is up!',

    'tool.curl.title': 'cURL Command Generator',
    'tool.curl.desc': 'Build cURL commands visually',
    'tool.curl.method': 'Method',
    'tool.curl.url': 'URL',
    'tool.curl.urlPlaceholder': 'https://api.example.com/users',
    'tool.curl.headers': 'Headers',
    'tool.curl.headerKey': 'Key',
    'tool.curl.headerValue': 'Value',
    'tool.curl.addHeader': 'Add Header',
    'tool.curl.body': 'Body',
    'tool.curl.bodyPlaceholder': 'JSON payload or form data...',
    'tool.curl.generate': 'Generate',
    'tool.curl.result': 'cURL Command',

    'tool.httpStatus.title': 'HTTP Status Codes',
    'tool.httpStatus.desc': 'Quick reference for all HTTP status codes',
    'tool.httpStatus.search': 'Search status code or name...',
    'tool.httpStatus.code': 'Code',
    'tool.httpStatus.name': 'Name',
    'tool.httpStatus.description': 'Description',

    'tool.unit.title': 'Unit Converter',
    'tool.unit.desc': 'Convert between length, weight, and temperature units',
    'tool.unit.value': 'Value',
    'tool.unit.from': 'From',
    'tool.unit.to': 'To',
    'tool.unit.swap': 'Swap',
    'tool.unit.result': 'Result',
    'tool.unit.length': 'Length',
    'tool.unit.weight': 'Weight',
    'tool.unit.temperature': 'Temperature',
    'unit.meter': 'Meter',
    'unit.kilometer': 'Kilometer',
    'unit.centimeter': 'Centimeter',
    'unit.millimeter': 'Millimeter',
    'unit.inch': 'Inch',
    'unit.foot': 'Foot',
    'unit.yard': 'Yard',
    'unit.mile': 'Mile',
    'unit.kilogram': 'Kilogram',
    'unit.gram': 'Gram',
    'unit.milligram': 'Milligram',
    'unit.pound': 'Pound',
    'unit.ounce': 'Ounce',
    'unit.celsius': 'Celsius',
    'unit.fahrenheit': 'Fahrenheit',
    'unit.kelvin': 'Kelvin',

    'tool.markdown.title': 'Markdown Preview',
    'tool.markdown.desc': 'Live preview for Markdown with basic syntax support',
    'tool.markdown.placeholder': 'Enter Markdown here...',
    'tool.markdown.preview': 'Preview',

    'tool.meta.title': 'Meta Tag Generator',
    'tool.meta.desc': 'Generate HTML meta tags for SEO and social sharing',
    'tool.meta.pageTitle': 'Page Title',
    'tool.meta.description': 'Description',
    'tool.meta.keywords': 'Keywords (comma separated)',
    'tool.meta.author': 'Author',
    'tool.meta.image': 'Image URL (for Open Graph)',
    'tool.meta.generate': 'Generate',
    'tool.meta.result': 'Meta Tags',

    'tool.tldr.title': 'TL;DR Generator',
    'tool.tldr.desc': 'Extract a concise summary from long text',
    'tool.tldr.placeholder': 'Paste long text here...',
    'tool.tldr.sentences': 'Sentences',
    'tool.tldr.summarize': 'Summarize',
    'tool.tldr.summary': 'Summary',
    'tool.tldr.originalLength': 'Original',
    'tool.tldr.summaryLength': 'Summary',
    'tool.tldr.compression': 'Compression',

    'tool.imageBase64.title': 'Image to Base64',
    'tool.imageBase64.desc': 'Convert images to Base64 data URLs',
    'tool.imageBase64.select': 'Select Image',
    'tool.imageBase64.preview': 'Preview',
    'tool.imageBase64.fileSize': 'File Size',
    'tool.imageBase64.base64Size': 'Base64 Size',
    'tool.imageBase64.result': 'Base64 Result',

    'tool.prDesc.title': 'PR Description Generator',
    'tool.prDesc.desc': 'Generate standardized pull request descriptions',
    'tool.prDesc.prTitle': 'PR Title',
    'tool.prDesc.changes': 'Changes',
    'tool.prDesc.changePlaceholder': 'Describe a change...',
    'tool.prDesc.addChange': 'Add Change',
    'tool.prDesc.testing': 'Testing Checklist',
    'tool.prDesc.unitTests': 'Unit tests pass',
    'tool.prDesc.integrationTests': 'Integration tests pass',
    'tool.prDesc.manualTesting': 'Manual testing completed',
    'tool.prDesc.relatedIssues': 'Related Issues',
    'tool.prDesc.generate': 'Generate',
    'tool.prDesc.result': 'PR Description',

    'tool.codeReview.title': 'Code Review Checklist',
    'tool.codeReview.desc': 'Ensure quality with a systematic review checklist',
    'tool.codeReview.quality': 'Code Quality',
    'tool.codeReview.security': 'Security',
    'tool.codeReview.performance': 'Performance',
    'tool.codeReview.maintainability': 'Maintainability',
    'tool.codeReview.progress': 'Progress',
    'tool.codeReview.itemQuality1': 'Code follows project style guidelines',
    'tool.codeReview.itemQuality2': 'Variable and function names are descriptive',
    'tool.codeReview.itemQuality3': 'No hardcoded values (use constants/config)',
    'tool.codeReview.itemQuality4': 'Error handling is implemented',
    'tool.codeReview.itemQuality5': 'No debug statements left',
    'tool.codeReview.itemSecurity1': 'No sensitive data in code',
    'tool.codeReview.itemSecurity2': 'Input validation is present',
    'tool.codeReview.itemSecurity3': 'Authentication/authorization checked',
    'tool.codeReview.itemPerformance1': 'No unnecessary re-renders',
    'tool.codeReview.itemPerformance2': 'Database queries are optimized',
    'tool.codeReview.itemPerformance3': 'Large files/assets are lazy-loaded',
    'tool.codeReview.itemMaintainability1': 'Code is documented with comments',
    'tool.codeReview.itemMaintainability2': 'Tests are added/updated',
    'tool.codeReview.itemMaintainability3': 'No dead code',
    'tool.codeReview.itemMaintainability4': 'Dependencies are justified',

    'tool.changelog.title': 'Changelog Generator',
    'tool.changelog.desc': 'Generate Keep a Changelog formatted entries',
    'tool.changelog.version': 'Version',
    'tool.changelog.date': 'Date',
    'tool.changelog.added': 'Added',
    'tool.changelog.changed': 'Changed',
    'tool.changelog.deprecated': 'Deprecated',
    'tool.changelog.removed': 'Removed',
    'tool.changelog.fixed': 'Fixed',
    'tool.changelog.security': 'Security',
    'tool.changelog.addItem': 'Add Item',
    'tool.changelog.generate': 'Generate',
    'tool.changelog.result': 'Changelog',

    'tool.seoTitle.title': 'SEO Title Optimizer',
    'tool.seoTitle.desc': 'Check and optimize page titles for search engines',
    'tool.seoTitle.inputTitle': 'Page Title',
    'tool.seoTitle.keyword': 'Target Keyword',
    'tool.seoTitle.brand': 'Brand Name',
    'tool.seoTitle.analyze': 'Analyze',
    'tool.seoTitle.length': 'Length',
    'tool.seoTitle.tooShort': 'Too short (< 30)',
    'tool.seoTitle.optimal': 'Optimal (50-60)',
    'tool.seoTitle.tooLong': 'Too long (> 60)',
    'tool.seoTitle.hasKeyword': 'Contains keyword',
    'tool.seoTitle.missingKeyword': 'Missing keyword',
    'tool.seoTitle.hasBrand': 'Contains brand',
    'tool.seoTitle.missingBrand': 'Missing brand',
    'tool.seoTitle.specialChars': 'Special characters',

    'tool.push.title': 'Push Notification Generator',
    'tool.push.desc': 'Generate push notification payloads for iOS, Android, and Web',
    'tool.push.platform': 'Platform',
    'tool.push.ios': 'iOS (APNs)',
    'tool.push.android': 'Android (FCM)',
    'tool.push.web': 'Web Push',
    'tool.push.notificationTitle': 'Title',
    'tool.push.body': 'Body',
    'tool.push.badge': 'Badge Count',
    'tool.push.sound': 'Sound',
    'tool.push.generate': 'Generate',
    'tool.push.result': 'Payload',

    'tool.baseConvert.title': 'Base Converter',
    'tool.baseConvert.desc': 'Convert numbers between binary, octal, decimal, and hexadecimal',
    'tool.baseConvert.input': 'Input number',
    'tool.baseConvert.from': 'From base',
    'tool.baseConvert.to': 'To base',
    'tool.baseConvert.convert': 'Convert',
    'tool.baseConvert.result': 'Result',

    'tool.cron.title': 'Cron Expression Parser',
    'tool.cron.desc': 'Parse and explain cron expressions in human-readable text',
    'tool.cron.input': 'Cron expression',
    'tool.cron.parse': 'Parse',
    'tool.cron.result': 'Meaning',
    'tool.cron.nextRuns': 'Next 5 runs',
    'tool.cron.invalid': 'Invalid cron expression',

    'tool.faq.title': 'FAQ Generator',
    'tool.faq.desc': 'Generate structured FAQ schema from Q&A pairs',
    'tool.faq.add': 'Add question',
    'tool.faq.question': 'Question',
    'tool.faq.answer': 'Answer',
    'tool.faq.remove': 'Remove',
    'tool.faq.format': 'Format',
    'tool.faq.html': 'HTML',
    'tool.faq.jsonLd': 'JSON-LD',
    'tool.faq.result': 'Output',

    'tool.sql.title': 'SQL Formatter',
    'tool.sql.desc': 'Format and beautify SQL queries',
    'tool.sql.input': 'SQL query',
    'tool.sql.format': 'Format',
    'tool.sql.result': 'Formatted SQL',

    'tool.tagline.title': 'Tagline Generator',
    'tool.tagline.desc': 'Generate catchy taglines and slogans for your product or brand',
    'tool.tagline.product': 'Product or brand name',
    'tool.tagline.category': 'Category',
    'tool.tagline.tone': 'Tone',
    'tool.tagline.toneProfessional': 'Professional',
    'tool.tagline.toneFun': 'Fun',
    'tool.tagline.toneBold': 'Bold',
    'tool.tagline.toneMinimal': 'Minimal',
    'tool.tagline.generate': 'Generate',
    'tool.tagline.result': 'Taglines',

    'tool.coldEmail.title': 'Cold Email Generator',
    'tool.coldEmail.desc': 'Generate personalized cold outreach emails',
    'tool.coldEmail.name': 'Your name',
    'tool.coldEmail.company': 'Your company',
    'tool.coldEmail.recipient': "Recipient's name",
    'tool.coldEmail.recipientCompany': "Recipient's company",
    'tool.coldEmail.purpose': 'Purpose',
    'tool.coldEmail.generate': 'Generate',
    'tool.coldEmail.result': 'Email',

    'tool.newsletter.title': 'Newsletter Formatter',
    'tool.newsletter.desc': 'Format newsletters with subject, preview, and body sections',
    'tool.newsletter.subject': 'Subject',
    'tool.newsletter.preview': 'Preview text',
    'tool.newsletter.body': 'Body content',
    'tool.newsletter.cta': 'Call to action',
    'tool.newsletter.format': 'Format',
    'tool.newsletter.result': 'Formatted Newsletter',

    'tool.xPost.title': 'X Post Generator',
    'tool.xPost.desc': 'Generate engaging posts for X/Twitter with character count',
    'tool.xPost.topic': 'Topic',
    'tool.xPost.tone': 'Tone',
    'tool.xPost.toneCasual': 'Casual',
    'tool.xPost.toneProfessional': 'Professional',
    'tool.xPost.toneWitty': 'Witty',
    'tool.xPost.generate': 'Generate',
    'tool.xPost.result': 'Posts',
    'tool.xPost.chars': 'chars',

    'tool.videoTitle.title': 'Video Title Generator',
    'tool.videoTitle.desc': 'Generate click-worthy YouTube video titles',
    'tool.videoTitle.topic': 'Video topic',
    'tool.videoTitle.style': 'Style',
    'tool.videoTitle.styleHowTo': 'How-To',
    'tool.videoTitle.styleList': 'Listicle',
    'tool.videoTitle.styleQuestion': 'Question',
    'tool.videoTitle.styleBold': 'Bold Claim',
    'tool.videoTitle.generate': 'Generate',
    'tool.videoTitle.result': 'Titles',

    'tool.ytScript.title': 'YouTube Script Generator',
    'tool.ytScript.desc': 'Generate structured video script outlines',
    'tool.ytScript.topic': 'Video topic',
    'tool.ytScript.duration': 'Duration (minutes)',
    'tool.ytScript.generate': 'Generate',
    'tool.ytScript.result': 'Script Outline',
    'tool.ytScript.hook': 'Hook',
    'tool.ytScript.intro': 'Introduction',
    'tool.ytScript.body': 'Main Content',
    'tool.ytScript.cta': 'Call to Action',

    'tool.adCopy.title': 'Ad Copy Generator',
    'tool.adCopy.desc': 'Generate compelling ad copy for your product or service',
    'tool.adCopy.product': 'Product/Service',
    'tool.adCopy.audience': 'Target audience',
    'tool.adCopy.platform': 'Platform',
    'tool.adCopy.platformGoogle': 'Google Ads',
    'tool.adCopy.platformMeta': 'Meta/Facebook',
    'tool.adCopy.platformLinkedIn': 'LinkedIn',
    'tool.adCopy.generate': 'Generate',
    'tool.adCopy.result': 'Ad Copy',

    'tool.shell.title': 'Shell Command Explainer',
    'tool.shell.desc': 'Explain what a shell command does in plain English',
    'tool.shell.input': 'Shell command',
    'tool.shell.explain': 'Explain',
    'tool.shell.result': 'Explanation',

    'tool.codeExplain.title': 'Code Explainer',
    'tool.codeExplain.desc': 'Explain what a code snippet does in plain language',
    'tool.codeExplain.input': 'Code snippet',
    'tool.codeExplain.language': 'Language',
    'tool.codeExplain.explain': 'Explain',
    'tool.codeExplain.result': 'Explanation',

    'tool.humanize.title': 'AI Text Humanizer',
    'tool.humanize.desc': 'Make AI-generated text sound more natural and human',
    'tool.humanize.input': 'AI-generated text',
    'tool.humanize.humanize': 'Humanize',
    'tool.humanize.result': 'Humanized text',

    'tool.ipLookup.title': 'IP Address Tool',
    'tool.ipLookup.desc': 'Validate, analyze, and get information about IP addresses',
    'tool.ipLookup.input': 'IP address',
    'tool.ipLookup.validate': 'Validate',
    'tool.ipLookup.valid': 'Valid IPv4 address',
    'tool.ipLookup.invalid': 'Invalid IP address',
    'tool.ipLookup.type': 'Type',
    'tool.ipLookup.private': 'Private',
    'tool.ipLookup.public': 'Public',
    'tool.ipLookup.loopback': 'Loopback',
    'tool.ipLookup.broadcast': 'Broadcast',
    'tool.ipLookup.networkClass': 'Network class',

    'tool.docs.title': 'Docstring Generator',
    'tool.docs.desc': 'Generate documentation comments for functions and methods',
    'tool.docs.input': 'Function signature',
    'tool.docs.language': 'Language',
    'tool.docs.generate': 'Generate',
    'tool.docs.result': 'Documentation',

    'tool.altText.title': 'Alt Text Generator',
    'tool.altText.desc': 'Generate accessible alt text for images from descriptions',
    'tool.altText.input': 'Image description',
    'tool.altText.generate': 'Generate',
    'tool.altText.result': 'Alt text',

    'tool.blogOutline.title': 'Blog Outline Generator',
    'tool.blogOutline.desc': 'Generate structured blog post outlines from a topic',
    'tool.blogOutline.topic': 'Blog topic',
    'tool.blogOutline.sections': 'Number of sections',
    'tool.blogOutline.generate': 'Generate',
    'tool.blogOutline.result': 'Outline',

    'tool.linkedin.title': 'LinkedIn Post Generator',
    'tool.linkedin.desc': 'Generate professional LinkedIn posts',
    'tool.linkedin.topic': 'Topic',
    'tool.linkedin.tone': 'Tone',
    'tool.linkedin.toneThoughtful': 'Thoughtful',
    'tool.linkedin.toneSuccess': 'Success Story',
    'tool.linkedin.toneOpinion': 'Opinion',
    'tool.linkedin.generate': 'Generate',
    'tool.linkedin.result': 'Post',

    'tool.lpHero.title': 'Landing Page Hero Generator',
    'tool.lpHero.desc': 'Generate hero section copy for landing pages',
    'tool.lpHero.product': 'Product name',
    'tool.lpHero.benefit': 'Main benefit',
    'tool.lpHero.audience': 'Target audience',
    'tool.lpHero.generate': 'Generate',
    'tool.lpHero.headline': 'Headline',
    'tool.lpHero.subheadline': 'Subheadline',
    'tool.lpHero.cta': 'Call to Action',

    'tool.cssGradient.title': 'CSS Gradient Generator',
    'tool.cssGradient.desc': 'Generate beautiful CSS gradients with live preview',
    'tool.cssGradient.type': 'Gradient type',
    'tool.cssGradient.linear': 'Linear',
    'tool.cssGradient.radial': 'Radial',
    'tool.cssGradient.angle': 'Angle',
    'tool.cssGradient.colors': 'Colors',
    'tool.cssGradient.addColor': 'Add color',
    'tool.cssGradient.remove': 'Remove',
    'tool.cssGradient.generate': 'Generate CSS',
    'tool.cssGradient.result': 'CSS',
    'tool.cssGradient.preview': 'Preview',

    'tool.pseudo.title': 'Pseudocode Generator',
    'tool.pseudo.desc': 'Turn natural language descriptions into structured pseudocode',
    'tool.pseudo.input': 'Describe the algorithm',
    'tool.pseudo.generate': 'Generate',
    'tool.pseudo.result': 'Pseudocode',

    'tool.diffPro.title': 'Advanced Diff',
    'tool.diffPro.desc': 'Compare two texts line-by-line with detailed change detection',
    'tool.diffPro.left': 'Original text',
    'tool.diffPro.right': 'Modified text',
    'tool.diffPro.compare': 'Compare',
    'tool.diffPro.added': 'Added',
    'tool.diffPro.removed': 'Removed',
    'tool.diffPro.unchanged': 'Unchanged',

    'tool.qrcode.title': 'QR Code Generator',
    'tool.qrcode.desc': 'Generate QR codes for URLs, text, and contact info',
    'tool.qrcode.input': 'Text or URL',
    'tool.qrcode.size': 'Size',
    'tool.qrcode.generate': 'Generate',
    'tool.qrcode.download': 'Download',

    // footer
    'footer.product': 'Product',
    'footer.games': 'Games',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.terms': 'Terms',
    'footer.copyright': '© 2026 AIHues · Find your AI vibe · Built on Kimi',
    'footer.tagline': 'Find your AI vibe. 57 tools + 3 games that feel human.',

    // playbooks
    'playbooks.badge1': 'AI Vibe Navigator',
    'playbooks.badge2': 'Built on Kimi',
    'playbooks.title': 'AIHues Growth Stack + AI Tools',
    'playbooks.desc':
      '100+ tools covering growth, AI products, open-source tracking, and design.',
  },
  zh: {
    // nav
    'nav.home': '首页',
    'nav.tools': '工具',
    'nav.games': '游戏',
    'nav.blog': '博客',
    'nav.wishlist': '许愿单',
    'nav.ranking': '排行榜',
    'nav.discover': '发现',
    'nav.login': '登录',

    // hero
    'hero.title': '找到你的',
    'hero.aiVibe': 'AI vibe',
    'hero.subtitle':
      '57+ AI 工具、小游戏和实用工具，开箱即用。告诉我们你的需求。',
    'hero.searchPlaceholder': "例如 '解析 JWT'... (按 / 聚焦)",
    'hero.askAI': '问 AI',

    // categories
    'categories.title': '按分类浏览',
    'categories.seeAll': '查看全部工具 →',
    'cat.utility': '常用小工具',
    'cat.developer': '开发者工具',
    'cat.aiWriting': 'AI 写作',
    'cat.games': '小游戏',
    'cat.utilityDesc': '字数统计、文本对比、全角转换、可读性、人性化',
    'cat.developerDesc': 'JWT、JSON、正则、Base64、UUID、二维码、SHA256',
    'cat.aiWritingDesc': 'X 推文、博客大纲、SEO 标题、新闻稿、PR 描述',
    'cat.gamesDesc': '每日幸运签、老虎机、投篮挑战 — 赚取积分',

    // stats
    'stats.aiTools': 'AI 工具',
    'stats.devTools': '开发工具',
    'stats.games': '小游戏',
    'stats.freeCredits': '免费积分',
    'stats.dayStreak': '连续签到',

    // sections
    'section.devTools': '开发者工具',
    'section.newThisWeek': '本周上新',
    'section.tools': '个工具',
    'section.allTools': '全部工具 →',
    'section.writingTools': '写作工具',
    'section.gameCenter': '游戏中心',
    'section.creditBalance': '当前积分',
    'section.viewAll': '查看全部 →',
    'section.popularTools': '热门工具',
    'section.dualEngine': '工具 + 游戏双引擎',
    'section.dualEngineDesc':
      '用工具提高效率，再玩个小游戏放松。57 个工具 + 3 款游戏 = 完整平台。',
    'section.browseAll': '浏览全部工具 →',
    'section.wishlistTitle': '找不到你需要的？',
    'section.wishlistDesc': '提交你的想法。最受欢迎的请求优先开发。',
    'section.submitIdea': '提交你的想法 →',

    // games
    'game.draw': '抽签 →',
    'game.spin': '旋转 →',
    'game.play': '开始 →',
    'game.dailyLuckDesc': '每日抽签获取箴言和积分奖励',
    'game.slotMachineDesc': '每日 3 次免费旋转，赢取大奖',
    'game.basketballDesc': '60 秒内获得最高分',
    'game.daily': '每日',
    'game.popular': '热门',
    'game.skill': '技巧',

    // credit
    'credit.title': '积分规则',
    'credit.initial': '初始奖励',
    'credit.initialDesc': '新用户赠送 100 积分',
    'credit.playToEarn': '玩游戏赚积分',
    'credit.playToEarnDesc': '每局游戏 +5~100 积分',
    'credit.useTools': '使用工具',
    'credit.useToolsDesc': '高级工具消耗积分解锁',
    'credit.dailyCheckin': '每日签到',
    'credit.dailyCheckinDesc': '每日 +10 积分，连签有加成',
    'credit.howItWorks': '积分规则',
    'credit.yourCredits': '当前积分',
    'credit.perGame': '积分/局',

    // sidebar
    'sidebar.allTools': '全部工具',
    'sidebar.growth': '出海增长',
    'sidebar.devTools': '开发者工具',
    'sidebar.utilities': '常用小工具',
    'sidebar.aiProducts': 'AI 产品推荐',
    'sidebar.openSource': '开源追踪',
    'sidebar.design': '设计工具',
    'sidebar.miniGames': '小游戏',

    // price filter
    'price.all': '全部',
    'price.free': '免费',
    'price.freemium': '免费增值',
    'price.paid': '付费',

    // tools
    'tool.wordCount.title': '字数统计',
    'tool.wordCount.desc': '实时统计字符数、字数和行数',
    'tool.wordCount.placeholder': '在此粘贴或输入文本...',
    'tool.wordCount.chars': '字符数',
    'tool.wordCount.charsNoSpace': '无空格',
    'tool.wordCount.words': '字数',
    'tool.wordCount.lines': '行数',
    'tool.wordCount.paragraphs': '段落数',
    'tool.wordCount.readTime': '阅读时间',
    'tool.wordCount.clear': '清空',
    'tool.wordCount.copy': '复制',

    'tool.base64.title': 'Base64 编码 / 解码',
    'tool.base64.desc': '即时编码和解码 Base64 字符串',
    'tool.base64.placeholder': '输入要编码的文本或要解码的 Base64...',
    'tool.base64.encode': '编码',
    'tool.base64.decode': '解码',
    'tool.base64.result': '结果',
    'tool.base64.urlSafe': 'URL 安全模式',

    'tool.urlEncode.title': 'URL 编码 / 解码',
    'tool.urlEncode.desc': '即时编码和解码 URL 字符串',
    'tool.urlEncode.placeholder': '输入要编码的文本或要解码的 URL 编码文本...',
    'tool.urlEncode.encode': '编码',
    'tool.urlEncode.decode': '解码',
    'tool.urlEncode.result': '结果',

    'tool.uuid.title': 'UUID 生成器',
    'tool.uuid.desc': '即时生成随机 UUID v4 标识符',
    'tool.uuid.generate': '生成',
    'tool.uuid.generate5': '生成 5 个',
    'tool.uuid.generate10': '生成 10 个',
    'tool.uuid.history': '历史记录',
    'tool.uuid.copy': '复制',
    'tool.uuid.copyAll': '复制全部',

    'tool.jwt.title': 'JWT 解析器',
    'tool.jwt.desc': '解码和检查 JSON Web Token',
    'tool.jwt.placeholder': '在此粘贴 JWT 令牌...',
    'tool.jwt.parse': '解析',
    'tool.jwt.header': 'Header',
    'tool.jwt.payload': 'Payload',
    'tool.jwt.signature': '签名',
    'tool.jwt.expired': '已过期',
    'tool.jwt.valid': '有效',
    'tool.jwt.expiresAt': '过期时间',

    'tool.json.title': 'JSON 格式化',
    'tool.json.desc': '即时格式化、验证和压缩 JSON',
    'tool.json.placeholder': '在此粘贴 JSON...',
    'tool.json.format': '格式化',
    'tool.json.minify': '压缩',
    'tool.json.validate': '验证',
    'tool.json.result': '结果',
    'tool.json.invalid': '无效的 JSON',

    'tool.sha256.title': 'SHA-256 哈希',
    'tool.sha256.desc': '计算任意文本的 SHA-256 哈希值',
    'tool.sha256.placeholder': '输入要哈希的文本...',
    'tool.sha256.hash': '哈希',
    'tool.sha256.result': '结果',

    'tool.lorem.title': 'Lorem Ipsum 生成器',
    'tool.lorem.desc': '为设计生成占位文本',
    'tool.lorem.paragraphs': '段落数',
    'tool.lorem.sentences': '每段句子数',
    'tool.lorem.generate': '生成',
    'tool.lorem.copy': '复制',

    'tool.timestamp.title': '时间戳转换器',
    'tool.timestamp.desc': '在 Unix 时间戳和人类可读日期之间转换',
    'tool.timestamp.placeholder': '输入 Unix 时间戳或 ISO 日期...',
    'tool.timestamp.convert': '转换',
    'tool.timestamp.local': '本地时间',
    'tool.timestamp.utc': 'UTC',
    'tool.timestamp.unixSeconds': 'Unix 秒',
    'tool.timestamp.unixMs': 'Unix 毫秒',
    'tool.timestamp.relative': '相对时间',

    'tool.htmlEntity.title': 'HTML 实体编码 / 解码',
    'tool.htmlEntity.desc': '编码和解码 HTML 实体',
    'tool.htmlEntity.placeholder': '输入文本或 HTML 实体...',
    'tool.htmlEntity.encode': '编码',
    'tool.htmlEntity.decode': '解码',
    'tool.htmlEntity.result': '结果',

    'tool.fullwidth.title': '全角转换器',
    'tool.fullwidth.desc': '在半角和全角字符之间转换',
    'tool.fullwidth.placeholder': '输入要转换的文本...',
    'tool.fullwidth.toFull': '转全角',
    'tool.fullwidth.toHalf': '转半角',
    'tool.fullwidth.result': '结果',

    'tool.password.title': '密码生成器',
    'tool.password.desc': '即时生成强安全密码',
    'tool.password.length': '长度',
    'tool.password.uppercase': '大写字母 (A-Z)',
    'tool.password.lowercase': '小写字母 (a-z)',
    'tool.password.numbers': '数字 (0-9)',
    'tool.password.symbols': '符号 (!@#$...)',
    'tool.password.generate': '生成',
    'tool.password.copy': '复制',
    'tool.password.strength': '强度',

    'tool.regex.title': '正则测试器',
    'tool.regex.desc': '实时测试正则表达式',
    'tool.regex.pattern': '正则表达式',
    'tool.regex.patternPlaceholder': '输入正则表达式...',
    'tool.regex.flags': '标志',
    'tool.regex.testText': '测试文本',
    'tool.regex.testTextPlaceholder': '输入要测试的文本...',
    'tool.regex.matches': '匹配结果',
    'tool.regex.noMatches': '无匹配结果',
    'tool.regex.groups': '捕获组',
    'tool.regex.error': '无效的正则表达式',

    'tool.diff.title': '文本对比',
    'tool.diff.desc': '逐行对比两段文本',
    'tool.diff.textA': '文本 A',
    'tool.diff.textB': '文本 B',
    'tool.diff.compare': '对比',
    'tool.diff.unchanged': '未变更',
    'tool.diff.removed': '删除',
    'tool.diff.added': '新增',
    'tool.diff.copy': '复制',

    'tool.csvJson.title': 'CSV / JSON 转换器',
    'tool.csvJson.desc': '在 CSV 和 JSON 格式之间转换',
    'tool.csvJson.placeholder': '在此粘贴 CSV 或 JSON...',
    'tool.csvJson.convert': '转换',
    'tool.csvJson.result': '结果',

    'tool.color.title': '颜色转换器',
    'tool.color.desc': '在 HEX、RGB 和 HSL 颜色格式之间转换',
    'tool.color.placeholder': '输入 HEX (例如 #b45309) 或 rgb(...)...',
    'tool.color.convert': '转换',
    'tool.color.hex': 'HEX',
    'tool.color.rgb': 'RGB',
    'tool.color.hsl': 'HSL',
    'tool.color.preview': '预览',

    'tool.titleCase.title': '文本大小写转换器',
    'tool.titleCase.desc': '在大写、小写、标题大小写等格式之间转换文本',
    'tool.titleCase.placeholder': '输入要转换的文本...',
    'tool.titleCase.uppercase': '全大写',
    'tool.titleCase.lowercase': '全小写',
    'tool.titleCase.titleCase': '标题大小写',
    'tool.titleCase.sentenceCase': '句子大小写',
    'tool.titleCase.camelCase': '驼峰式',
    'tool.titleCase.snakeCase': '蛇形',
    'tool.titleCase.kebabCase': '短横线',
    'tool.titleCase.result': '结果',

    'tool.gitCommit.title': 'Git 提交信息生成器',
    'tool.gitCommit.desc': '生成符合 Conventional Commits 格式的提交信息',
    'tool.gitCommit.type': '类型',
    'tool.gitCommit.scope': '范围（可选）',
    'tool.gitCommit.description': '描述',
    'tool.gitCommit.body': '正文（可选）',
    'tool.gitCommit.footer': '页脚（可选）',
    'tool.gitCommit.generate': '生成',
    'tool.gitCommit.result': '提交信息',
    'tool.gitCommit.copy': '复制',

    'gitCommit.feat': 'feat: 新功能',
    'gitCommit.fix': 'fix: 修复 Bug',
    'gitCommit.docs': 'docs: 仅文档变更',
    'gitCommit.style': 'style: 代码风格变更',
    'gitCommit.refactor': 'refactor: 代码重构',
    'gitCommit.perf': 'perf: 性能优化',
    'gitCommit.test': 'test: 添加或更新测试',
    'gitCommit.chore': 'chore: 构建/流程变更',

    'tool.readability.title': '可读性评分',
    'tool.readability.desc': '使用 Flesch-Kincaid 指标分析文本可读性',
    'tool.readability.placeholder': '粘贴要分析的文本...',
    'tool.readability.analyze': '分析',
    'tool.readability.words': '字数',
    'tool.readability.sentences': '句子数',
    'tool.readability.avgSentenceLength': '平均句长',
    'tool.readability.syllables': '音节数',
    'tool.readability.fleschEase': 'Flesch 易读度',
    'tool.readability.fleschGrade': 'Flesch-Kincaid 等级',
    'tool.readability.rating': '评级',
    'tool.readability.veryEasy': '非常简单',
    'tool.readability.easy': '简单',
    'tool.readability.fairlyEasy': '较简单',
    'tool.readability.standard': '标准',
    'tool.readability.fairlyDifficult': '较困难',
    'tool.readability.difficult': '困难',
    'tool.readability.veryDifficult': '非常困难',

    'tool.pomodoro.title': '番茄钟',
    'tool.pomodoro.desc': '用 25 分钟专注技巧保持专注',
    'tool.pomodoro.start': '开始',
    'tool.pomodoro.pause': '暂停',
    'tool.pomodoro.reset': '重置',
    'tool.pomodoro.minutes': '分钟',
    'tool.pomodoro.done': '时间到！',

    'tool.curl.title': 'cURL 命令生成器',
    'tool.curl.desc': '可视化构建 cURL 命令',
    'tool.curl.method': '方法',
    'tool.curl.url': 'URL',
    'tool.curl.urlPlaceholder': 'https://api.example.com/users',
    'tool.curl.headers': '请求头',
    'tool.curl.headerKey': '键',
    'tool.curl.headerValue': '值',
    'tool.curl.addHeader': '添加请求头',
    'tool.curl.body': '请求体',
    'tool.curl.bodyPlaceholder': 'JSON 负载或表单数据...',
    'tool.curl.generate': '生成',
    'tool.curl.result': 'cURL 命令',

    'tool.httpStatus.title': 'HTTP 状态码',
    'tool.httpStatus.desc': '所有 HTTP 状态码速查',
    'tool.httpStatus.search': '搜索状态码或名称...',
    'tool.httpStatus.code': '代码',
    'tool.httpStatus.name': '名称',
    'tool.httpStatus.description': '描述',

    'tool.unit.title': '单位转换器',
    'tool.unit.desc': '在长度、重量和温度单位之间转换',
    'tool.unit.value': '数值',
    'tool.unit.from': '从',
    'tool.unit.to': '到',
    'tool.unit.swap': '交换',
    'tool.unit.result': '结果',
    'tool.unit.length': '长度',
    'tool.unit.weight': '重量',
    'tool.unit.temperature': '温度',
    'unit.meter': '米',
    'unit.kilometer': '千米',
    'unit.centimeter': '厘米',
    'unit.millimeter': '毫米',
    'unit.inch': '英寸',
    'unit.foot': '英尺',
    'unit.yard': '码',
    'unit.mile': '英里',
    'unit.kilogram': '千克',
    'unit.gram': '克',
    'unit.milligram': '毫克',
    'unit.pound': '磅',
    'unit.ounce': '盎司',
    'unit.celsius': '摄氏度',
    'unit.fahrenheit': '华氏度',
    'unit.kelvin': '开尔文',

    'tool.markdown.title': 'Markdown 预览',
    'tool.markdown.desc': 'Markdown 基础语法实时预览',
    'tool.markdown.placeholder': '在此输入 Markdown...',
    'tool.markdown.preview': '预览',

    'tool.meta.title': 'Meta 标签生成器',
    'tool.meta.desc': '生成 SEO 和社交分享的 HTML meta 标签',
    'tool.meta.pageTitle': '页面标题',
    'tool.meta.description': '描述',
    'tool.meta.keywords': '关键词（逗号分隔）',
    'tool.meta.author': '作者',
    'tool.meta.image': '图片 URL（用于 Open Graph）',
    'tool.meta.generate': '生成',
    'tool.meta.result': 'Meta 标签',

    'tool.tldr.title': 'TL;DR 生成器',
    'tool.tldr.desc': '从长文本中提取简洁摘要',
    'tool.tldr.placeholder': '在此粘贴长文本...',
    'tool.tldr.sentences': '句子数',
    'tool.tldr.summarize': '摘要',
    'tool.tldr.summary': '摘要',
    'tool.tldr.originalLength': '原文',
    'tool.tldr.summaryLength': '摘要',
    'tool.tldr.compression': '压缩率',

    'tool.imageBase64.title': '图片转 Base64',
    'tool.imageBase64.desc': '将图片转换为 Base64 数据 URL',
    'tool.imageBase64.select': '选择图片',
    'tool.imageBase64.preview': '预览',
    'tool.imageBase64.fileSize': '文件大小',
    'tool.imageBase64.base64Size': 'Base64 大小',
    'tool.imageBase64.result': 'Base64 结果',

    'tool.prDesc.title': 'PR 描述生成器',
    'tool.prDesc.desc': '生成标准化的 Pull Request 描述',
    'tool.prDesc.prTitle': 'PR 标题',
    'tool.prDesc.changes': '变更',
    'tool.prDesc.changePlaceholder': '描述一个变更...',
    'tool.prDesc.addChange': '添加变更',
    'tool.prDesc.testing': '测试清单',
    'tool.prDesc.unitTests': '单元测试通过',
    'tool.prDesc.integrationTests': '集成测试通过',
    'tool.prDesc.manualTesting': '手动测试完成',
    'tool.prDesc.relatedIssues': '相关 Issues',
    'tool.prDesc.generate': '生成',
    'tool.prDesc.result': 'PR 描述',

    'tool.codeReview.title': '代码审查清单',
    'tool.codeReview.desc': '用系统化审查清单确保代码质量',
    'tool.codeReview.quality': '代码质量',
    'tool.codeReview.security': '安全性',
    'tool.codeReview.performance': '性能',
    'tool.codeReview.maintainability': '可维护性',
    'tool.codeReview.progress': '进度',
    'tool.codeReview.itemQuality1': '代码遵循项目风格规范',
    'tool.codeReview.itemQuality2': '变量和函数名具有描述性',
    'tool.codeReview.itemQuality3': '无硬编码值（使用常量/配置）',
    'tool.codeReview.itemQuality4': '已实现错误处理',
    'tool.codeReview.itemQuality5': '无遗留调试语句',
    'tool.codeReview.itemSecurity1': '代码中无敏感数据',
    'tool.codeReview.itemSecurity2': '存在输入验证',
    'tool.codeReview.itemSecurity3': '已检查认证/授权',
    'tool.codeReview.itemPerformance1': '无不必要的重新渲染',
    'tool.codeReview.itemPerformance2': '数据库查询已优化',
    'tool.codeReview.itemPerformance3': '大文件/资源已懒加载',
    'tool.codeReview.itemMaintainability1': '代码有注释文档',
    'tool.codeReview.itemMaintainability2': '已添加/更新测试',
    'tool.codeReview.itemMaintainability3': '无死代码',
    'tool.codeReview.itemMaintainability4': '依赖项有合理理由',

    'tool.changelog.title': 'Changelog 生成器',
    'tool.changelog.desc': '生成 Keep a Changelog 格式的变更日志',
    'tool.changelog.version': '版本',
    'tool.changelog.date': '日期',
    'tool.changelog.added': '新增',
    'tool.changelog.changed': '变更',
    'tool.changelog.deprecated': '弃用',
    'tool.changelog.removed': '移除',
    'tool.changelog.fixed': '修复',
    'tool.changelog.security': '安全',
    'tool.changelog.addItem': '添加条目',
    'tool.changelog.generate': '生成',
    'tool.changelog.result': 'Changelog',

    // footer
    'footer.product': '产品',
    'footer.games': '游戏',
    'footer.company': '公司',
    'footer.about': '关于',
    'footer.terms': '条款',
    'footer.copyright': '© 2026 AIHues · 找到你的 AI vibe · 基于 Kimi 构建',
    'footer.tagline': '找到你的 AI vibe。57 个工具 + 3 款游戏，自然流畅。',

    // playbooks
    'playbooks.badge1': 'AI Vibe Navigator',
    'playbooks.badge2': '基于 Kimi 构建',
    'playbooks.title': 'AIHues 出海增长 + AI 工具导航',
    'tool.seoTitle.title': 'SEO 标题优化器',
    'tool.seoTitle.desc': '检查并优化搜索引擎页面标题',
    'tool.seoTitle.inputTitle': '页面标题',
    'tool.seoTitle.keyword': '目标关键词',
    'tool.seoTitle.brand': '品牌名',
    'tool.seoTitle.analyze': '分析',
    'tool.seoTitle.length': '长度',
    'tool.seoTitle.tooShort': '太短 (< 30)',
    'tool.seoTitle.optimal': '最佳 (50-60)',
    'tool.seoTitle.tooLong': '太长 (> 60)',
    'tool.seoTitle.hasKeyword': '包含关键词',
    'tool.seoTitle.missingKeyword': '缺少关键词',
    'tool.seoTitle.hasBrand': '包含品牌',
    'tool.seoTitle.missingBrand': '缺少品牌',
    'tool.seoTitle.specialChars': '特殊字符',

    'tool.push.title': '推送通知生成器',
    'tool.push.desc': '生成 iOS、Android 和 Web 推送通知负载',
    'tool.push.platform': '平台',
    'tool.push.ios': 'iOS (APNs)',
    'tool.push.android': 'Android (FCM)',
    'tool.push.web': 'Web 推送',
    'tool.push.notificationTitle': '标题',
    'tool.push.body': '正文',
    'tool.push.badge': '角标数',
    'tool.push.sound': '声音',
    'tool.push.generate': '生成',
    'tool.push.result': 'Payload',

    'tool.baseConvert.title': '进制转换器',
    'tool.baseConvert.desc': '在二进制、八进制、十进制和十六进制之间转换数字',
    'tool.baseConvert.input': '输入数字',
    'tool.baseConvert.from': '原进制',
    'tool.baseConvert.to': '目标进制',
    'tool.baseConvert.convert': '转换',
    'tool.baseConvert.result': '结果',

    'tool.cron.title': 'Cron 表达式解析器',
    'tool.cron.desc': '将 Cron 表达式解析为人类可读的文本',
    'tool.cron.input': 'Cron 表达式',
    'tool.cron.parse': '解析',
    'tool.cron.result': '含义',
    'tool.cron.nextRuns': '接下来 5 次执行',
    'tool.cron.invalid': '无效的 Cron 表达式',

    'tool.faq.title': 'FAQ 生成器',
    'tool.faq.desc': '从问答对生成结构化的 FAQ 模式',
    'tool.faq.add': '添加问题',
    'tool.faq.question': '问题',
    'tool.faq.answer': '答案',
    'tool.faq.remove': '删除',
    'tool.faq.format': '格式',
    'tool.faq.html': 'HTML',
    'tool.faq.jsonLd': 'JSON-LD',
    'tool.faq.result': '输出',

    'tool.sql.title': 'SQL 格式化器',
    'tool.sql.desc': '格式化和美化 SQL 查询',
    'tool.sql.input': 'SQL 查询',
    'tool.sql.format': '格式化',
    'tool.sql.result': '格式化后的 SQL',

    'tool.tagline.title': '标语生成器',
    'tool.tagline.desc': '为您的产品或品牌生成 catchy 标语和口号',
    'tool.tagline.product': '产品或品牌名称',
    'tool.tagline.category': '类别',
    'tool.tagline.tone': '语气',
    'tool.tagline.toneProfessional': '专业',
    'tool.tagline.toneFun': '有趣',
    'tool.tagline.toneBold': '大胆',
    'tool.tagline.toneMinimal': '极简',
    'tool.tagline.generate': '生成',
    'tool.tagline.result': '标语',

    'tool.coldEmail.title': 'Cold Email 生成器',
    'tool.coldEmail.desc': '生成个性化的 Cold Outreach 邮件',
    'tool.coldEmail.name': '您的姓名',
    'tool.coldEmail.company': '您的公司',
    'tool.coldEmail.recipient': '收件人姓名',
    'tool.coldEmail.recipientCompany': '收件人公司',
    'tool.coldEmail.purpose': '目的',
    'tool.coldEmail.generate': '生成',
    'tool.coldEmail.result': '邮件',

    'tool.newsletter.title': 'Newsletter 格式化器',
    'tool.newsletter.desc': '格式化 Newsletter，包含主题、预览和正文部分',
    'tool.newsletter.subject': '主题',
    'tool.newsletter.preview': '预览文本',
    'tool.newsletter.body': '正文内容',
    'tool.newsletter.cta': '行动号召',
    'tool.newsletter.format': '格式化',
    'tool.newsletter.result': '格式化后的 Newsletter',

    'tool.xPost.title': 'X 帖子生成器',
    'tool.xPost.desc': '为 X/Twitter 生成吸引人的帖子，含字符计数',
    'tool.xPost.topic': '主题',
    'tool.xPost.tone': '语气',
    'tool.xPost.toneCasual': '随意',
    'tool.xPost.toneProfessional': '专业',
    'tool.xPost.toneWitty': '机智',
    'tool.xPost.generate': '生成',
    'tool.xPost.result': '帖子',
    'tool.xPost.chars': '字符',

    'tool.videoTitle.title': '视频标题生成器',
    'tool.videoTitle.desc': '生成吸引眼球的 YouTube 视频标题',
    'tool.videoTitle.topic': '视频主题',
    'tool.videoTitle.style': '风格',
    'tool.videoTitle.styleHowTo': '教程',
    'tool.videoTitle.styleList': '列表',
    'tool.videoTitle.styleQuestion': '疑问',
    'tool.videoTitle.styleBold': '大胆声明',
    'tool.videoTitle.generate': '生成',
    'tool.videoTitle.result': '标题',

    'tool.ytScript.title': 'YouTube 脚本生成器',
    'tool.ytScript.desc': '生成结构化的视频脚本大纲',
    'tool.ytScript.topic': '视频主题',
    'tool.ytScript.duration': '时长（分钟）',
    'tool.ytScript.generate': '生成',
    'tool.ytScript.result': '脚本大纲',
    'tool.ytScript.hook': '开场',
    'tool.ytScript.intro': '介绍',
    'tool.ytScript.body': '主体内容',
    'tool.ytScript.cta': '行动号召',

    'tool.adCopy.title': '广告文案生成器',
    'tool.adCopy.desc': '为您的产品或服务生成引人注目的广告文案',
    'tool.adCopy.product': '产品/服务',
    'tool.adCopy.audience': '目标受众',
    'tool.adCopy.platform': '平台',
    'tool.adCopy.platformGoogle': 'Google Ads',
    'tool.adCopy.platformMeta': 'Meta/Facebook',
    'tool.adCopy.platformLinkedIn': 'LinkedIn',
    'tool.adCopy.generate': '生成',
    'tool.adCopy.result': '广告文案',

    'tool.shell.title': 'Shell 命令解释器',
    'tool.shell.desc': '用通俗易懂的语言解释 Shell 命令的作用',
    'tool.shell.input': 'Shell 命令',
    'tool.shell.explain': '解释',
    'tool.shell.result': '解释',

    'tool.codeExplain.title': '代码解释器',
    'tool.codeExplain.desc': '用通俗语言解释代码片段的作用',
    'tool.codeExplain.input': '代码片段',
    'tool.codeExplain.language': '语言',
    'tool.codeExplain.explain': '解释',
    'tool.codeExplain.result': '解释',

    'tool.humanize.title': 'AI 文本人性化',
    'tool.humanize.desc': '让 AI 生成的文本听起来更自然、更像人类写作',
    'tool.humanize.input': 'AI 生成的文本',
    'tool.humanize.humanize': '人性化',
    'tool.humanize.result': '人性化后的文本',

    'tool.ipLookup.title': 'IP 地址工具',
    'tool.ipLookup.desc': '验证、分析并获取 IP 地址信息',
    'tool.ipLookup.input': 'IP 地址',
    'tool.ipLookup.validate': '验证',
    'tool.ipLookup.valid': '有效的 IPv4 地址',
    'tool.ipLookup.invalid': '无效的 IP 地址',
    'tool.ipLookup.type': '类型',
    'tool.ipLookup.private': '私有',
    'tool.ipLookup.public': '公网',
    'tool.ipLookup.loopback': '回环',
    'tool.ipLookup.broadcast': '广播',
    'tool.ipLookup.networkClass': '网络类别',

    'tool.docs.title': '文档注释生成器',
    'tool.docs.desc': '为函数和方法生成文档注释',
    'tool.docs.input': '函数签名',
    'tool.docs.language': '语言',
    'tool.docs.generate': '生成',
    'tool.docs.result': '文档',

    'tool.altText.title': 'Alt 文本生成器',
    'tool.altText.desc': '根据描述生成可访问的图片 Alt 文本',
    'tool.altText.input': '图片描述',
    'tool.altText.generate': '生成',
    'tool.altText.result': 'Alt 文本',

    'tool.blogOutline.title': '博客大纲生成器',
    'tool.blogOutline.desc': '根据主题生成结构化的博客文章大纲',
    'tool.blogOutline.topic': '博客主题',
    'tool.blogOutline.sections': '章节数',
    'tool.blogOutline.generate': '生成',
    'tool.blogOutline.result': '大纲',

    'tool.linkedin.title': 'LinkedIn 帖子生成器',
    'tool.linkedin.desc': '生成专业的 LinkedIn 帖子',
    'tool.linkedin.topic': '主题',
    'tool.linkedin.tone': '语气',
    'tool.linkedin.toneThoughtful': '深思',
    'tool.linkedin.toneSuccess': '成功案例',
    'tool.linkedin.toneOpinion': '观点',
    'tool.linkedin.generate': '生成',
    'tool.linkedin.result': '帖子',

    'tool.lpHero.title': '落地页 Hero 生成器',
    'tool.lpHero.desc': '生成落地页 Hero 部分的文案',
    'tool.lpHero.product': '产品名称',
    'tool.lpHero.benefit': '主要优势',
    'tool.lpHero.audience': '目标受众',
    'tool.lpHero.generate': '生成',
    'tool.lpHero.headline': '主标题',
    'tool.lpHero.subheadline': '副标题',
    'tool.lpHero.cta': '行动号召',

    'tool.cssGradient.title': 'CSS 渐变生成器',
    'tool.cssGradient.desc': '生成漂亮的 CSS 渐变并实时预览',
    'tool.cssGradient.type': '渐变类型',
    'tool.cssGradient.linear': '线性',
    'tool.cssGradient.radial': '径向',
    'tool.cssGradient.angle': '角度',
    'tool.cssGradient.colors': '颜色',
    'tool.cssGradient.addColor': '添加颜色',
    'tool.cssGradient.remove': '删除',
    'tool.cssGradient.generate': '生成 CSS',
    'tool.cssGradient.result': 'CSS',
    'tool.cssGradient.preview': '预览',

    'tool.pseudo.title': '伪代码生成器',
    'tool.pseudo.desc': '将自然语言描述转换为结构化伪代码',
    'tool.pseudo.input': '描述算法',
    'tool.pseudo.generate': '生成',
    'tool.pseudo.result': '伪代码',

    'tool.diffPro.title': '高级文本对比',
    'tool.diffPro.desc': '逐行对比两段文本，详细检测变更',
    'tool.diffPro.left': '原始文本',
    'tool.diffPro.right': '修改后的文本',
    'tool.diffPro.compare': '对比',
    'tool.diffPro.added': '新增',
    'tool.diffPro.removed': '删除',
    'tool.diffPro.unchanged': '未变更',

    'tool.qrcode.title': 'QR 码生成器',
    'tool.qrcode.desc': '为 URL、文本和联系信息生成 QR 码',
    'tool.qrcode.input': '文本或 URL',
    'tool.qrcode.size': '尺寸',
    'tool.qrcode.generate': '生成',
    'tool.qrcode.download': '下载',

    'playbooks.desc': '100+ 工具覆盖出海增长、AI 产品、开源追踪和设计领域。',
  },
};

export function t(locale: Locale, key: string): string {
  return dict[locale][key] ?? dict.en[key] ?? key;
}
