/* ── AIHues Complete Tool Database ──
   90 tools: 58 local + 32 growth (external links)
   Frontend supplement when API returns incomplete data.
*/

export type PriceTag = 'free' | 'freemium' | 'paid';

export interface ToolData {
  slug: string;
  icon: string;
  name: string;
  nameZh: string;
  description: string;
  descriptionZh: string;
  category: string;
  price: PriceTag;
  credit: number;
  url: string;
  isExternal: boolean;
}

export const TOOL_CATEGORIES = [
  { key: 'all', label: 'All Tools', labelZh: '全部工具', icon: '📁' },
  { key: 'developer', label: 'Developer', labelZh: '开发者工具', icon: '💻' },
  { key: 'utility', label: 'Utility', labelZh: '常用小工具', icon: '🛠️' },
  { key: 'ai-writing', label: 'AI Writing', labelZh: 'AI 写作', icon: '🤖' },
  { key: 'growth', label: 'Growth', labelZh: '出海增长', icon: '🚀' },
  { key: 'community', label: 'Community', labelZh: '社区目录', icon: '🗺️' },
  { key: 'seo', label: 'SEO', labelZh: 'SEO', icon: '🔍' },
  { key: 'analytics', label: 'Analytics', labelZh: '分析埋点', icon: '📊' },
  { key: 'content', label: 'Content', labelZh: '内容创作', icon: '🎨' },
  { key: 'games', label: 'Games', labelZh: '小游戏', icon: '🎮' },
] as const;

export type ToolCategoryKey = (typeof TOOL_CATEGORIES)[number]['key'];

/* ── Local tools (internal pages) ── */
export const LOCAL_TOOLS: ToolData[] = [
  /* Developer */
  {
    slug: 'jwt',
    icon: '🔐',
    name: 'JWT Parser',
    nameZh: 'JWT解析',
    description: 'Parse JWT tokens',
    descriptionZh: '解析JWT令牌',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/jwt',
    isExternal: false,
  },
  {
    slug: 'json',
    icon: '📋',
    name: 'JSON Formatter',
    nameZh: 'JSON格式化',
    description: 'Format & validate JSON',
    descriptionZh: '格式化和校验JSON',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/json',
    isExternal: false,
  },
  {
    slug: 'regex',
    icon: '🔍',
    name: 'Regex Tester',
    nameZh: '正则测试',
    description: 'Test regular expressions',
    descriptionZh: '测试正则表达式',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/regex',
    isExternal: false,
  },
  {
    slug: 'uuid',
    icon: '🆔',
    name: 'UUID Generator',
    nameZh: 'UUID生成',
    description: 'Generate UUID v4',
    descriptionZh: '生成UUID v4',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/uuid',
    isExternal: false,
  },
  {
    slug: 'timestamp',
    icon: '⏱️',
    name: 'Timestamp',
    nameZh: '时间戳',
    description: 'Unix timestamp converter',
    descriptionZh: 'Unix时间戳转换',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/timestamp',
    isExternal: false,
  },
  {
    slug: 'base64',
    icon: '🔢',
    name: 'Base64',
    nameZh: 'Base64',
    description: 'Base64 encode/decode',
    descriptionZh: 'Base64编解码',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/base64',
    isExternal: false,
  },
  {
    slug: 'sha256',
    icon: '🔒',
    name: 'SHA256 Hash',
    nameZh: 'SHA256',
    description: 'SHA-256/SHA-1/MD5',
    descriptionZh: 'SHA哈希计算',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/sha256',
    isExternal: false,
  },
  {
    slug: 'sql',
    icon: '🗄️',
    name: 'SQL Formatter',
    nameZh: 'SQL格式化',
    description: 'Format SQL queries',
    descriptionZh: '格式化SQL查询',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/sql',
    isExternal: false,
  },
  {
    slug: 'url-encode',
    icon: '🔗',
    name: 'URL Encode',
    nameZh: 'URL编码',
    description: 'URL encode/decode',
    descriptionZh: 'URL编码解码',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/url-encode',
    isExternal: false,
  },
  {
    slug: 'base-convert',
    icon: '🔢',
    name: 'Base Converter',
    nameZh: '进制转换',
    description: 'Binary/octal/dec/hex',
    descriptionZh: '进制转换器',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/base-convert',
    isExternal: false,
  },
  {
    slug: 'password-gen',
    icon: '🔑',
    name: 'Password Gen',
    nameZh: '密码生成',
    description: 'Secure password gen',
    descriptionZh: '安全密码生成',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/password-gen',
    isExternal: false,
  },
  {
    slug: 'http-status',
    icon: '🌐',
    name: 'HTTP Status',
    nameZh: 'HTTP状态码',
    description: 'Status code reference',
    descriptionZh: 'HTTP状态码参考',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/http-status',
    isExternal: false,
  },
  {
    slug: 'html-entity',
    icon: '◈',
    name: 'HTML Entity',
    nameZh: 'HTML实体',
    description: 'Entity & Unicode',
    descriptionZh: 'HTML实体转换',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/html-entity',
    isExternal: false,
  },
  {
    slug: 'cron-parser',
    icon: '⏰',
    name: 'Cron Parser',
    nameZh: 'Cron解析',
    description: 'Parse cron expressions',
    descriptionZh: '解析Cron表达式',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/cron-parser',
    isExternal: false,
  },
  {
    slug: 'code-explain',
    icon: '💻',
    name: 'Code Explain',
    nameZh: '代码解释',
    description: 'Explain code',
    descriptionZh: '代码解释',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/code-explain',
    isExternal: false,
  },
  {
    slug: 'code-review',
    icon: '👁️',
    name: 'Code Review',
    nameZh: '代码审查',
    description: 'Review code',
    descriptionZh: '代码审查',
    category: 'developer',
    price: 'freemium',
    credit: 15,
    url: '/tools/code-review',
    isExternal: false,
  },
  {
    slug: 'shell',
    icon: '🐚',
    name: 'Shell Gen',
    nameZh: 'Shell生成',
    description: 'Generate shell commands',
    descriptionZh: '生成Shell命令',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/shell',
    isExternal: false,
  },
  {
    slug: 'git-commit',
    icon: '📌',
    name: 'Git Commit',
    nameZh: 'Git提交',
    description: 'Git commit messages',
    descriptionZh: 'Git提交信息',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/git-commit',
    isExternal: false,
  },
  {
    slug: 'ip-lookup',
    icon: '🔍',
    name: 'IP Lookup',
    nameZh: 'IP查询',
    description: 'IP geolocation lookup',
    descriptionZh: 'IP地理位置查询',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/ip-lookup',
    isExternal: false,
  },
  {
    slug: 'curl-gen',
    icon: '🌐',
    name: 'Curl Gen',
    nameZh: 'Curl生成',
    description: 'Generate curl commands',
    descriptionZh: '生成cURL命令',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/curl-gen',
    isExternal: false,
  },
  {
    slug: 'image-to-base64',
    icon: '🖼️',
    name: 'Image → Base64',
    nameZh: '图片转Base64',
    description: 'Image to Base64',
    descriptionZh: '图片转Base64',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/image-to-base64',
    isExternal: false,
  },
  {
    slug: 'css-gradient',
    icon: '🌈',
    name: 'CSS Gradient',
    nameZh: 'CSS渐变',
    description: 'CSS gradient gen',
    descriptionZh: 'CSS渐变生成',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/css-gradient',
    isExternal: false,
  },
  {
    slug: 'color-convert',
    icon: '🎨',
    name: 'Color Converter',
    nameZh: '颜色转换',
    description: 'HEX/RGB/HSL/CMYK',
    descriptionZh: '颜色转换器',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/color-convert',
    isExternal: false,
  },
  {
    slug: 'csv-json',
    icon: '📊',
    name: 'CSV ↔ JSON',
    nameZh: 'CSV转JSON',
    description: 'CSV/JSON convert',
    descriptionZh: 'CSV/JSON转换',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/csv-json',
    isExternal: false,
  },
  {
    slug: 'diff-pro',
    icon: '📑',
    name: 'Diff Pro',
    nameZh: 'Diff Pro',
    description: 'Advanced text diff',
    descriptionZh: '高级文本对比',
    category: 'developer',
    price: 'freemium',
    credit: 10,
    url: '/tools/diff-pro',
    isExternal: false,
  },
  {
    slug: 'unit-convert',
    icon: '📐',
    name: 'Unit Convert',
    nameZh: '单位转换',
    description: 'Unit converter',
    descriptionZh: '单位转换器',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/unit-convert',
    isExternal: false,
  },
  {
    slug: 'qrcode',
    icon: '📱',
    name: 'QR Code',
    nameZh: '二维码',
    description: 'Generate QR codes',
    descriptionZh: '生成二维码',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/qrcode',
    isExternal: false,
  },
  {
    slug: 'markdown',
    icon: '📝',
    name: 'Markdown',
    nameZh: 'Markdown',
    description: 'Live MD preview',
    descriptionZh: '实时Markdown预览',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/markdown',
    isExternal: false,
  },
  {
    slug: 'pomodoro',
    icon: '🍅',
    name: 'Pomodoro',
    nameZh: '番茄钟',
    description: 'Focus timer',
    descriptionZh: '专注计时器',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/pomodoro',
    isExternal: false,
  },
  {
    slug: 'chi-squared',
    icon: '📊',
    name: 'Chi-Squared',
    nameZh: '卡方检验',
    description: 'A/B test calculator',
    descriptionZh: 'A/B测试计算器',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/chi-squared',
    isExternal: false,
  },
  /* Utility */
  {
    slug: 'word-count',
    icon: '📊',
    name: 'Word Counter',
    nameZh: '字数统计',
    description: 'Word & char count',
    descriptionZh: '字数统计',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/word-count',
    isExternal: false,
  },
  {
    slug: 'diff',
    icon: '📑',
    name: 'Diff Checker',
    nameZh: '文本对比',
    description: 'Compare text diffs',
    descriptionZh: '文本差异对比',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/diff',
    isExternal: false,
  },
  {
    slug: 'fullwidth',
    icon: '↔️',
    name: 'Fullwidth',
    nameZh: '全角转换',
    description: 'Width converter',
    descriptionZh: '全角半角转换',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/fullwidth',
    isExternal: false,
  },
  {
    slug: 'title-case',
    icon: '📰',
    name: 'Title Case',
    nameZh: '标题格式',
    description: '12 format types',
    descriptionZh: '标题格式转换',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/title-case',
    isExternal: false,
  },
  {
    slug: 'readability',
    icon: '📖',
    name: 'Readability',
    nameZh: '可读性',
    description: 'Text readability',
    descriptionZh: '文本可读性',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/readability',
    isExternal: false,
  },
  {
    slug: 'humanize',
    icon: '✨',
    name: 'Humanize',
    nameZh: '去AI味',
    description: 'De-AI text',
    descriptionZh: '去除AI痕迹',
    category: 'utility',
    price: 'freemium',
    credit: 10,
    url: '/tools/humanize',
    isExternal: false,
  },
  {
    slug: 'lorem-ipsum',
    icon: '📝',
    name: 'Lorem Ipsum',
    nameZh: '随机文本',
    description: 'Random text generator',
    descriptionZh: '随机文本生成',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/lorem-ipsum',
    isExternal: false,
  },
  {
    slug: 'seo-title',
    icon: '🔍',
    name: 'SEO Title',
    nameZh: 'SEO标题',
    description: 'SEO title generator',
    descriptionZh: 'SEO标题生成',
    category: 'utility',
    price: 'free',
    credit: 0,
    url: '/tools/seo-title',
    isExternal: false,
  },
  /* AI Writing */
  {
    slug: 'ad-copy',
    icon: '📢',
    name: 'Ad Copy',
    nameZh: '广告文案',
    description: '3 ad sets',
    descriptionZh: '3套广告文案',
    category: 'ai-writing',
    price: 'freemium',
    credit: 15,
    url: '/tools/ad-copy',
    isExternal: false,
  },
  {
    slug: 'alt-text',
    icon: '🖼️',
    name: 'Alt Text',
    nameZh: 'Alt文本',
    description: 'SEO alt text',
    descriptionZh: 'SEO Alt文本',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/alt-text',
    isExternal: false,
  },
  {
    slug: 'blog-outline',
    icon: '📝',
    name: 'Blog Outline',
    nameZh: '博客大纲',
    description: '6-section outline',
    descriptionZh: '6段博客大纲',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/blog-outline',
    isExternal: false,
  },
  {
    slug: 'changelog',
    icon: '📋',
    name: 'Changelog',
    nameZh: '更新日志',
    description: 'Categorized changelog',
    descriptionZh: '分类更新日志',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/changelog',
    isExternal: false,
  },
  {
    slug: 'cold-email',
    icon: '📧',
    name: 'Cold Email',
    nameZh: '冷邮件',
    description: '3 outreach templates',
    descriptionZh: '3个外联模板',
    category: 'ai-writing',
    price: 'freemium',
    credit: 10,
    url: '/tools/cold-email',
    isExternal: false,
  },
  {
    slug: 'docs',
    icon: '📚',
    name: 'Docs',
    nameZh: '文档',
    description: 'API docs',
    descriptionZh: 'API文档生成',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/docs',
    isExternal: false,
  },
  {
    slug: 'faq',
    icon: '❓',
    name: 'FAQ',
    nameZh: 'FAQ',
    description: '8 FAQ Q&A',
    descriptionZh: '8个FAQ问答',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/faq',
    isExternal: false,
  },
  {
    slug: 'linkedin',
    icon: '💼',
    name: 'LinkedIn',
    nameZh: 'LinkedIn',
    description: '3 post formats',
    descriptionZh: 'LinkedIn帖子',
    category: 'ai-writing',
    price: 'freemium',
    credit: 10,
    url: '/tools/linkedin',
    isExternal: false,
  },
  {
    slug: 'lp-hero',
    icon: '🎯',
    name: 'LP Hero',
    nameZh: '落地页',
    description: 'Landing page copy',
    descriptionZh: '落地页文案',
    category: 'ai-writing',
    price: 'freemium',
    credit: 20,
    url: '/tools/lp-hero',
    isExternal: false,
  },
  {
    slug: 'meta',
    icon: '🏷️',
    name: 'Meta',
    nameZh: 'Meta标签',
    description: 'SEO meta HTML',
    descriptionZh: 'SEO Meta标签',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/meta',
    isExternal: false,
  },
  {
    slug: 'newsletter',
    icon: '📰',
    name: 'Newsletter',
    nameZh: '新闻稿',
    description: 'Newsletter structure',
    descriptionZh: '新闻稿结构',
    category: 'ai-writing',
    price: 'freemium',
    credit: 15,
    url: '/tools/newsletter',
    isExternal: false,
  },
  {
    slug: 'pr-desc',
    icon: '🔀',
    name: 'PR Desc',
    nameZh: 'PR描述',
    description: 'PR template',
    descriptionZh: 'PR描述模板',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/pr-desc',
    isExternal: false,
  },
  {
    slug: 'pseudo',
    icon: '🎭',
    name: 'Pseudo',
    nameZh: '伪代码',
    description: 'Pseudocode generator',
    descriptionZh: '伪代码生成',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/pseudo',
    isExternal: false,
  },
  {
    slug: 'push',
    icon: '🔔',
    name: 'Push',
    nameZh: '推送',
    description: '4 push copies',
    descriptionZh: '推送通知文案',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/push',
    isExternal: false,
  },
  {
    slug: 'tagline',
    icon: '✒️',
    name: 'Tagline',
    nameZh: '标语',
    description: '8 brand taglines',
    descriptionZh: '品牌标语',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/tagline',
    isExternal: false,
  },
  {
    slug: 'tldr',
    icon: '📄',
    name: 'TL;DR',
    nameZh: '摘要',
    description: 'Summary extract',
    descriptionZh: '摘要提取',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/tldr',
    isExternal: false,
  },
  {
    slug: 'video-title',
    icon: '🎬',
    name: 'Video Title',
    nameZh: '视频标题',
    description: '8 YouTube titles',
    descriptionZh: 'YouTube标题',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/video-title',
    isExternal: false,
  },
  {
    slug: 'x-post',
    icon: '𝕏',
    name: 'X Post',
    nameZh: 'X推文',
    description: '3 X post formats',
    descriptionZh: 'X帖子格式',
    category: 'ai-writing',
    price: 'free',
    credit: 0,
    url: '/tools/x-post',
    isExternal: false,
  },
  {
    slug: 'yt-script',
    icon: '🎥',
    name: 'YT Script',
    nameZh: '脚本',
    description: 'YouTube script',
    descriptionZh: 'YouTube脚本',
    category: 'ai-writing',
    price: 'freemium',
    credit: 20,
    url: '/tools/yt-script',
    isExternal: false,
  },
  {
    slug: 'kimi-code',
    icon: '📘',
    name: 'Kimi Code Cheat Sheet',
    nameZh: 'Kimi Code 速查表',
    description:
      'Quick reference for Kimi Code CLI commands, shortcuts and prompts',
    descriptionZh: '常用 Kimi Code CLI 命令、快捷键和提示词速查',
    category: 'developer',
    price: 'free',
    credit: 0,
    url: '/tools/kimi-code',
    isExternal: false,
  },
];

/* ── Growth tools (external links) ── */
export const GROWTH_TOOLS: ToolData[] = [
  {
    slug: 'toolify-social',
    icon: '📡',
    name: 'Toolify Social',
    nameZh: 'Toolify社媒监听',
    description: 'AI social listening',
    descriptionZh: 'AI 社媒监听',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://www.toolify.ai/social-listening',
    isExternal: true,
  },
  {
    slug: 'vizzylabs',
    icon: '📊',
    name: 'Vizzylabs',
    nameZh: 'Vizzylabs',
    description: 'Viral content analysis',
    descriptionZh: '爆款内容分析',
    category: 'growth',
    price: 'free',
    credit: 0,
    url: 'https://app.vizzylabs.ai/trending',
    isExternal: true,
  },
  {
    slug: 'tweet-binder',
    icon: '🐦',
    name: 'Tweet Binder',
    nameZh: 'Tweet Binder',
    description: 'Twitter tracker',
    descriptionZh: 'Twitter 转化率监控',
    category: 'growth',
    price: 'paid',
    credit: 30,
    url: 'https://www.tweetbinder.com/',
    isExternal: true,
  },
  {
    slug: 'ph-deck',
    icon: '🎯',
    name: 'PH Deck',
    nameZh: 'PH Deck',
    description: 'PH featured tracker',
    descriptionZh: 'PH 产品追踪',
    category: 'growth',
    price: 'free',
    credit: 0,
    url: 'https://www.phdeck.com/',
    isExternal: true,
  },
  {
    slug: 'ai-hub',
    icon: '💬',
    name: 'AI HUB',
    nameZh: 'AI HUB',
    description: 'Discord AI community',
    descriptionZh: 'Discord AI 社区',
    category: 'community',
    price: 'free',
    credit: 0,
    url: 'https://discord.gg/aihub',
    isExternal: true,
  },
  {
    slug: 'reddit-ml',
    icon: '🔴',
    name: 'r/MachineLearning',
    nameZh: 'r/ML',
    description: 'Reddit ML community',
    descriptionZh: 'Reddit ML 社区',
    category: 'community',
    price: 'free',
    credit: 0,
    url: 'https://reddit.com/r/MachineLearning',
    isExternal: true,
  },
  {
    slug: 'hackernews',
    icon: '🟠',
    name: 'Hacker News',
    nameZh: 'HN',
    description: 'Top dev community',
    descriptionZh: '顶级开发者社区',
    category: 'community',
    price: 'free',
    credit: 0,
    url: 'https://news.ycombinator.com',
    isExternal: true,
  },
  {
    slug: 'indiehackers',
    icon: '🛠️',
    name: 'Indie Hackers',
    nameZh: 'IndieHackers',
    description: 'Indie devs',
    descriptionZh: '独立开发者社区',
    category: 'community',
    price: 'free',
    credit: 0,
    url: 'https://indiehackers.com',
    isExternal: true,
  },
  {
    slug: 'dev-to',
    icon: '💻',
    name: 'Dev.to',
    nameZh: 'Dev.to',
    description: 'Dev blog platform',
    descriptionZh: '开发者博客',
    category: 'community',
    price: 'free',
    credit: 0,
    url: 'https://dev.to',
    isExternal: true,
  },
  {
    slug: 'eezycollab',
    icon: '🤝',
    name: 'EEzycollab',
    nameZh: 'EEzycollab',
    description: 'KOL matching + email',
    descriptionZh: 'KOL 匹配',
    category: 'growth',
    price: 'freemium',
    credit: 20,
    url: 'https://www.eezycollab.com',
    isExternal: true,
  },
  {
    slug: 'nanoinfluencer',
    icon: '👥',
    name: 'Nanoinfluencer',
    nameZh: 'Nanoinfluencer',
    description: 'KOL research',
    descriptionZh: 'KOL 调研',
    category: 'growth',
    price: 'freemium',
    credit: 20,
    url: 'https://www.nanoinfluencer.ai',
    isExternal: true,
  },
  {
    slug: 'noxinfluencer',
    icon: '🔍',
    name: 'NoxInfluencer',
    nameZh: 'NoxInfluencer',
    description: 'Influencer DB',
    descriptionZh: '红人数据库',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://cn.noxinfluencer.com',
    isExternal: true,
  },
  {
    slug: 'geelark',
    icon: '🦜',
    name: 'GeeLark',
    nameZh: 'GeeLark',
    description: 'AI social marketing',
    descriptionZh: 'AI 社媒助手',
    category: 'growth',
    price: 'paid',
    credit: 30,
    url: 'https://www.geelark.com',
    isExternal: true,
  },
  {
    slug: 'dmpro',
    icon: '✉️',
    name: 'DMpro.ai',
    nameZh: 'DMpro',
    description: 'X auto DM',
    descriptionZh: 'X 自动 DM',
    category: 'growth',
    price: 'paid',
    credit: 35,
    url: 'https://www.dmpro.ai',
    isExternal: true,
  },
  {
    slug: 'phantombuster',
    icon: '👻',
    name: 'Phantombuster',
    nameZh: 'Phantombuster',
    description: 'LinkedIn automation',
    descriptionZh: 'LinkedIn 自动化',
    category: 'growth',
    price: 'paid',
    credit: 30,
    url: 'https://phantombuster.com',
    isExternal: true,
  },
  {
    slug: 'reddit-strategy',
    icon: '🤖',
    name: 'Reddit Strategy',
    nameZh: 'Reddit策略',
    description: 'AI Reddit strategy',
    descriptionZh: 'AI Reddit 策略',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://leapility.com',
    isExternal: true,
  },
  {
    slug: 'reddit-pain',
    icon: '🎯',
    name: 'Reddit Pain',
    nameZh: 'Reddit痛点',
    description: 'Pain analysis',
    descriptionZh: '痛点分析',
    category: 'growth',
    price: 'free',
    credit: 0,
    url: 'https://leapility.com',
    isExternal: true,
  },
  {
    slug: 'reddit-list',
    icon: '📋',
    name: 'Reddit List',
    nameZh: 'RedditList',
    description: 'Reddit directory',
    descriptionZh: 'Reddit 目录',
    category: 'community',
    price: 'free',
    credit: 0,
    url: 'https://www.reddit-list.com',
    isExternal: true,
  },
  {
    slug: 'aitdk',
    icon: '🔑',
    name: 'AITDK',
    nameZh: 'AITDK',
    description: 'AI SEO extension',
    descriptionZh: 'AI SEO 插件',
    category: 'seo',
    price: 'free',
    credit: 0,
    url: 'https://aitdk.com',
    isExternal: true,
  },
  {
    slug: 'keywords-everywhere',
    icon: '📈',
    name: 'Keywords Everywhere',
    nameZh: 'Keywords',
    description: 'Keyword volume tool',
    descriptionZh: '关键词插件',
    category: 'seo',
    price: 'freemium',
    credit: 10,
    url: 'https://keywordseverywhere.com',
    isExternal: true,
  },
  {
    slug: 'semrush',
    icon: '📊',
    name: 'Semrush',
    nameZh: 'Semrush',
    description: 'SEO platform',
    descriptionZh: 'SEO 分析',
    category: 'seo',
    price: 'paid',
    credit: 30,
    url: 'https://www.semrush.com',
    isExternal: true,
  },
  {
    slug: 'juicebox',
    icon: '🔗',
    name: 'Juicebox',
    nameZh: 'Juicebox',
    description: 'Short link + UTM',
    descriptionZh: 'Short link + UTM',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://juicebox.ai',
    isExternal: true,
  },
  {
    slug: 'bitly',
    icon: '⚡',
    name: 'Bitly',
    nameZh: 'Bitly',
    description: 'Short link benchmark',
    descriptionZh: '短链接标杆',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://bitly.com',
    isExternal: true,
  },
  {
    slug: 'mixpanel',
    icon: '📈',
    name: 'Mixpanel',
    nameZh: 'Mixpanel',
    description: 'User analytics',
    descriptionZh: '用户行为分析',
    category: 'analytics',
    price: 'freemium',
    credit: 20,
    url: 'https://mixpanel.com',
    isExternal: true,
  },
  {
    slug: 'posthog',
    icon: '🦔',
    name: 'PostHog',
    nameZh: 'PostHog',
    description: 'Open source analytics',
    descriptionZh: '开源用户分析',
    category: 'analytics',
    price: 'freemium',
    credit: 0,
    url: 'https://posthog.com',
    isExternal: true,
  },
  {
    slug: 'arcade',
    icon: '🎮',
    name: 'Arcade',
    nameZh: 'Arcade',
    description: 'Interactive demo',
    descriptionZh: '交互式 Demo',
    category: 'content',
    price: 'freemium',
    credit: 20,
    url: 'https://www.arcade.software',
    isExternal: true,
  },
  {
    slug: 'loops',
    icon: '📧',
    name: 'Loops',
    nameZh: 'Loops',
    description: 'Email automation',
    descriptionZh: '邮件自动化',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://loops.so',
    isExternal: true,
  },
  {
    slug: 'adquick',
    icon: '📢',
    name: 'AdQuick',
    nameZh: 'AdQuick',
    description: 'Billboard ads',
    descriptionZh: '广告牌平台',
    category: 'growth',
    price: 'paid',
    credit: 35,
    url: 'https://www.adquick.com',
    isExternal: true,
  },
  {
    slug: 'prolific',
    icon: '🔬',
    name: 'Prolific',
    nameZh: 'Prolific',
    description: 'User research',
    descriptionZh: '用户调研',
    category: 'growth',
    price: 'paid',
    credit: 30,
    url: 'https://www.prolific.com',
    isExternal: true,
  },
  {
    slug: 'qwoted',
    icon: '📰',
    name: 'Qwoted',
    nameZh: 'Qwoted',
    description: 'Media resources',
    descriptionZh: '媒体资源',
    category: 'growth',
    price: 'freemium',
    credit: 15,
    url: 'https://www.qwoted.com',
    isExternal: true,
  },
  {
    slug: 'glueclub',
    icon: '🤝',
    name: 'GlueClub',
    nameZh: 'GlueClub',
    description: 'Networking',
    descriptionZh: '建联平台',
    category: 'growth',
    price: 'paid',
    credit: 30,
    url: 'https://www.glueclub.com',
    isExternal: true,
  },
  {
    slug: 'rapidapi',
    icon: '⚡',
    name: 'RapidAPI',
    nameZh: 'RapidAPI',
    description: 'API marketplace',
    descriptionZh: 'API 市场',
    category: 'developer',
    price: 'freemium',
    credit: 15,
    url: 'https://rapidapi.com',
    isExternal: true,
  },
];

export const ALL_TOOLS: ToolData[] = [...LOCAL_TOOLS, ...GROWTH_TOOLS];

export function getToolBySlug(slug: string): ToolData | undefined {
  return ALL_TOOLS.find((t) => t.slug === slug);
}

export function getToolsByCategory(category: string): ToolData[] {
  if (category === 'all') return ALL_TOOLS;
  return ALL_TOOLS.filter((t) => t.category === category);
}

export function categoryCounts(): Record<string, number> {
  const counts: Record<string, number> = { all: ALL_TOOLS.length };
  for (const t of ALL_TOOLS) {
    counts[t.category] = (counts[t.category] || 0) + 1;
  }
  return counts;
}
