'use client';

import {
  Anchor,
  Bird,
  Blocks,
  Bomb,
  Boxes,
  Carrot,
  ChevronsDown,
  CircleDot,
  Grip,
  Plane,
  Slice,
  Swords,
  ArrowLeftRight,
  ArrowRightLeft,
  BarChart3,
  Bell,
  BookOpen,
  Brain,
  Calculator,
  CalendarClock,
  Clapperboard,
  ClipboardList,
  Clock,
  Code,
  Code2,
  Copy,
  Crown,
  Database,
  Dices,
  Drama,
  Eye,
  FileJson,
  FileText,
  FileCode2,
  Fingerprint,
  Gamepad2,
  GitCommit,
  GitCompare,
  GitPullRequest,
  Globe,
  Grid3x3,
  Hash,
  Heading,
  HelpCircle,
  Image,
  ImagePlus,
  Key,
  KeyRound,
  Languages,
  LayoutGrid,
  Lightbulb,
  Link,
  List,
  Lock,
  LucideIcon,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Newspaper,
  Paintbrush,
  Palette,
  PenTool,
  QrCode,
  Rocket,
  Ruler,
  ScrollText,
  Search,
  Sheet,
  Sparkles,
  Table,
  Tag,
  Target,
  Terminal,
  Timer,
  TrendingUp,
  Trophy,
  Type,
  Users,
  Video,
  Wand2,
  Workflow,
  Worm,
  Wrench,
} from 'lucide-react';

/* ── slug → Lucide icon mapping ─────────────────────────────── */
const TOOL_ICONS: Record<string, LucideIcon> = {
  /* Developer */
  jwt: Key,
  json: FileJson,
  regex: Search,
  uuid: Fingerprint,
  timestamp: Clock,
  base64: Hash,
  sha256: Lock,
  sql: Database,
  'url-encode': Link,
  'base-convert': ArrowRightLeft,
  'password-gen': KeyRound,
  'http-status': Globe,
  'html-entity': Code,
  'cron-parser': CalendarClock,
  'code-explain': Lightbulb,
  'code-review': Eye,
  shell: Terminal,
  'git-commit': GitCommit,
  'ip-lookup': MapPin,
  'curl-gen': Globe,
  'curl-to-code': FileCode2,
  'image-to-base64': Image,
  'css-gradient': Paintbrush,
  'color-convert': Palette,
  'csv-json': Table,
  'diff-pro': GitCompare,
  'unit-convert': Ruler,
  qrcode: QrCode,
  markdown: FileText,
  pomodoro: Timer,
  'chi-squared': Calculator,
  'kimi-code': BookOpen,
  mermaid: Workflow,

  /* Utility */
  'word-count': Type,
  diff: Copy,
  fullwidth: ArrowLeftRight,
  'title-case': Heading,
  readability: BookOpen,
  'cn-convert': Languages,
  'table-convert': Sheet,
  humanize: Sparkles,
  'lorem-ipsum': FileText,
  'seo-title': Search,

  /* AI Writing */
  'ad-copy': Megaphone,
  'alt-text': ImagePlus,
  'blog-outline': List,
  changelog: ScrollText,
  'cold-email': Mail,
  docs: BookOpen,
  faq: HelpCircle,
  linkedin: MessageSquare,
  'lp-hero': Target,
  meta: Tag,
  newsletter: Newspaper,
  'pr-desc': GitPullRequest,
  pseudo: Code2,
  push: Bell,
  tagline: PenTool,
  tldr: FileText,
  'video-title': Video,
  'x-post': MessageSquare,
  'yt-script': Clapperboard,

  /* Games */
  'doodle-jump': Rocket,
  'daily-luck': Sparkles,
  'slot-machine': Dices,
  basketball: Trophy,
  snake: Worm,
  'color-hunt': Grid3x3,
  chess: Crown,
  flappy: Bird,
  'block-drop': Blocks,
  'brick-breaker': Grip,
  'fruit-slash': Slice,
  minesweeper: Bomb,
  sudoku: Table,
  'sky-strike': Plane,
  'bullet-storm': Target,
  'dodge-arena': CircleDot,
  'hundred-floors': ChevronsDown,
  'depth-charge': Anchor,
  'combo-rush': Swords,
  'radish-smash': Carrot,
  'game-of-life': Boxes,

  /* Tests */
  sbti: Drama,
  mbti: Brain,
  tests: ClipboardList,

  /* Categories */
  all: LayoutGrid,
  developer: Code2,
  utility: Wrench,
  'ai-writing': Wand2,
  growth: TrendingUp,
  community: Users,
  seo: Search,
  analytics: BarChart3,
  content: PenTool,
  games: Gamepad2,

  /* Top-level groups */
  tools: Boxes,
  play: Dices,
  resources: BookOpen,
};

export function ToolIcon({
  slug,
  size = 20,
  className = '',
}: {
  slug: string;
  size?: number;
  className?: string;
}) {
  const Icon = TOOL_ICONS[slug];
  if (!Icon) return null;
  return <Icon size={size} strokeWidth={1.7} className={className} />;
}

export function hasToolIcon(slug: string): boolean {
  return slug in TOOL_ICONS;
}
