# https://dev.msh.team/engineering/devops/deploy-examples
#
# 必需修改项已标记为 1. 2. 3. 4.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  ############################################################
  # 1. ArgoCD 应用名，全局唯一
  name: aihues
  # namespace for this manifest, no need to change.
  namespace: argocd
spec:
  syncPolicy:
    # 启用自动部署
    automated:
      selfHeal: true
  project: test
  destination:
    server: 'https://10.41.72.68:6443'
    ############################################################
    # 应用部署的命名空间，一般无需修改
    namespace: marci-dev

  sources:
    # Web
    ############################################################
    # 2. 前端仓库地址，helm chart 相对路径，需要跟踪的分支/tag/commit
    - repoURL: 'https://dev.msh.team/search-engine/rec/aiushtha.git'
      path: deploy/aihues/web
      targetRevision: backend-api
      # helm 安装参数
      helm:
        parameters:
          - name: web.image.tag
            value: $ARGOCD_APP_REVISION_SHORT

    # API
    ############################################################
    # 3. 后端仓库地址，helm chart 相对路径，需要跟踪的分支/tag/commit
    - repoURL: 'https://dev.msh.team/search-engine/rec/aiushtha.git'
      path: deploy/aihues/api
      targetRevision: backend-api
      helm:
        valueFiles:
          - $values/aiushtha/aihues/api/test/values.yaml
          - $values/aiushtha/aihues/api/test/config.yaml
        parameters:
          - name: api.image.tag
            value: $ARGOCD_APP_REVISION_SHORT

    # config for API (referenced in `valueFiles` above)
    ############################################################
    # 4. 配置仓库地址，一般用来存放配置文件和敏感环境变量。需要遵循 values.yaml 的字段定义
    - repoURL: https://dev.msh.team/search-engine/marci-config.git
      targetRevision: master
      ref: values


  # source has no effect, leave it here for UI compatibility.
  source:
    repoURL: 'https://dev.msh.team/example.git'
    path: deploy/helm
    targetRevision: HEAD
