import type { ComponentType } from 'react';

// GENERATED by scripts/gen-story-registry.mjs — do not edit by hand.
import s0 from './ai-coding-assistants-copilot-vs-cody-vs-codeium';
import s1 from './ai-content-strategy';
import s2 from './ai-image-generation-for-marketing-a-cost-breakdown';
import s3 from './ai-productivity-stack';
import s4 from './ai-voice-cloning-use-cases-ethics-and-the-tools-that-get-it-';
import s5 from './api-design-for-humans-rest-graphql-or-trpc';
import s6 from './app-store-optimization-in-2026-beyond-keywords';
import s7 from './authentication-without-the-pain-oauth-passkeys-and-magic-lin';
import s8 from './autogpt-vs-agentic-workflows-what-actually-works-in-producti';
import s9 from './automation-scripts-that-save-me-10-hours-a-week';
import s10 from './building-a-micro-saas-empire-the-portfolio-approach';
import s11 from './building-a-personal-brand-on-linkedin-as-a-developer';
import s12 from './building-a-remote-first-company-from-day-one';
import s13 from './building-ai-products-without-a-phd-a-pragmatic-guide';
import s14 from './building-in-public-a-strategy-not-a-stunt';
import s15 from './claude-3-7-vs-gpt-4o-which-one-actually-writes-better-code';
import s16 from './cold-email-that-gets-replies-templates-and-psychology';
import s17 from './community-led-growth-the-playbook-for-2026';
import s18 from './content-clusters-the-strategy-that-doubled-our-organic-traff';
import s19 from './content-refresh-how-to-update-old-posts-for-new-rankings';
import s20 from './context-switching-is-killing-your-output-here-is-the-fix';
import s21 from './cursor-editor-10-features-that-will-change-how-you-code';
import s22 from './database-design-for-indie-devs-start-simple-scale-later';
import s23 from './dealing-with-imposter-syndrome-as-a-solo-founder';
import s24 from './deep-work-in-the-age-of-ai-is-focus-still-possible';
import s25 from './digital-minimalism-for-developers-a-30-day-challenge';
import s26 from './edge-computing-when-to-use-it-when-to-skip-it';
import s27 from './email-marketing-for-saas-beyond-the-welcome-sequence';
import s28 from './energy-management-vs-time-management';
import s29 from './from-employee-to-founder-the-mental-shift';
import s30 from './from-side-project-to-50k-arr-a-12-month-timeline';
import s31 from './growth-tools-2026';
import s32 from './how-to-build-an-ai-saas-in-48-hours-step-by-step';
import s33 from './how-to-create-a-viral-tool-that-markets-your-product';
import s34 from './how-to-evaluate-ai-tools-a-framework-for-teams';
import s35 from './how-to-get-your-first-1000-users-without-paid-ads';
import s36 from './how-to-hire-your-first-contractor-without-losing-money';
import s37 from './how-to-read-faster-without-losing-comprehension';
import s38 from './how-to-run-effective-1-1s-even-if-you-hate-meetings';
import s39 from './how-to-say-no-without-burning-bridges';
import s40 from './how-to-validate-your-saas-idea-in-one-weekend';
import s41 from './how-to-write-copy-that-sells-even-if-you-are-not-a-writer';
import s42 from './how-we-use-ai-to-cut-our-content-production-time-by-70';
import s43 from './keyword-research-in-2026-beyond-search-volume';
import s44 from './kimi-k2-6-open-source-coding-model-explained';
import s45 from './kimi-k2-open-agentic-intelligence-explained';
import s46 from './kimi-k2-thinking-the-reasoning-model-explained';
import s47 from './kol-marketing';
import s48 from './launching-on-product-hunt-what-worked-in-2026';
import s49 from './link-building-for-boring-b2b-products';
import s50 from './local-seo-for-saas-does-it-even-matter';
import s51 from './measuring-content-roi-metrics-that-matter-to-your-ceo';
import s52 from './midjourney-v7-review-the-good-the-bad-and-the-weird';
import s53 from './monorepos-in-2026-turborepo-nx-or-just-pnpm';
import s54 from './no-code-mvp';
import s55 from './open-source-ai-models-that-rival-gpt-4-in-2026';
import s56 from './prompt-engineering-is-dead-long-live-prompt-engineering';
import s57 from './react-server-components-a-practical-guide';
import s58 from './reddit-marketing';
import s59 from './referral-loops-how-dropbox-notion-and-linear-grew';
import s60 from './remote-work-burnout-signs-prevention-recovery';
import s61 from './running-llms-locally-a-complete-setup-guide-for-2026';
import s62 from './saas-pricing-strategies-that-actually-convert-in-2026';
import s63 from './schema-markup-that-actually-moves-the-needle';
import s64 from './seo-2026-trends';
import s65 from './seo-for-saas-the-long-tail-strategy-that-works';
import s66 from './solo-founding-one-year-of-lessons-and-regrets';
import s67 from './technical-seo-for-single-page-applications';
import s68 from './testing-strategies-for-small-teams';
import s69 from './the-4-hour-workweek-for-developers-reality-check';
import s70 from './the-5-minute-rule-for-starting-hard-tasks';
import s71 from './the-art-of-the-soft-launch-why-big-bangs-fail';
import s72 from './the-best-ai-tools-for-indie-developers-in-2026';
import s73 from './the-best-note-taking-apps-for-developers-in-2026';
import s74 from './the-bootstrapper-s-guide-to-raising-zero-dollars';
import s75 from './the-complete-guide-to-affiliate-marketing-for-saas';
import s76 from './the-complete-guide-to-ai-powered-customer-support';
import s77 from './the-dark-side-of-growth-hacking-what-not-to-do';
import s78 from './the-developer-s-second-brain-how-i-organize-everything';
import s79 from './the-emotional-rollercoaster-of-running-a-startup';
import s80 from './the-exit-strategy-when-to-sell-pivot-or-shut-down';
import s81 from './the-future-of-search-what-happens-when-ai-answers-everything';
import s82 from './the-hidden-costs-of-ai-writing-tools-nobody-talks-about';
import s83 from './the-legal-and-tax-basics-every-indie-dev-ignores';
import s84 from './the-minimum-viable-marketing-stack-for-indie-devs';
import s85 from './the-morning-routine-that-actually-works-for-night-owls';
import s86 from './the-problem-with-productivity-porn';
import s87 from './the-rise-of-ai-agents-hype-vs-reality';
import s88 from './the-rise-of-local-first-apps-sync-without-the-cloud';
import s89 from './the-state-of-css-in-2026-tailwind-panda-and-beyond';
import s90 from './the-state-of-indie-hacker-marketing-in-2026';
import s91 from './the-tech-stack-that-scales-from-0-to-1m-arr';
import s92 from './time-blocking-for-creatives-a-realistic-guide';
import s93 from './twitter-growth';
import s94 from './video-seo-how-to-rank-on-youtube-and-google';
import s95 from './web-performance-in-2026-core-web-vitals-and-beyond';
import s96 from './why-i-stopped-chasing-vc-and-started-building-for-profit';
import s97 from './why-i-switched-from-chatgpt-to-perplexity-for-research';
import s98 from './why-most-side-projects-never-become-businesses';
import s99 from './why-your-ai-generated-content-sounds-generic-and-how-to-fix-';
import s100 from './why-your-ai-generated-content-sounds-generic-and-how-to-fix-it';
import s101 from './why-your-landing-page-is-not-converting-and-how-to-fix-it';
import s102 from './worldvqa-atomic-world-knowledge-benchmark-explained';

export const GENERATED_SCENES: Record<string, ComponentType> = {
  'ai-coding-assistants-copilot-vs-cody-vs-codeium': s0,
  'ai-content-strategy': s1,
  'ai-image-generation-for-marketing-a-cost-breakdown': s2,
  'ai-productivity-stack': s3,
  'ai-voice-cloning-use-cases-ethics-and-the-tools-that-get-it-': s4,
  'api-design-for-humans-rest-graphql-or-trpc': s5,
  'app-store-optimization-in-2026-beyond-keywords': s6,
  'authentication-without-the-pain-oauth-passkeys-and-magic-lin': s7,
  'autogpt-vs-agentic-workflows-what-actually-works-in-producti': s8,
  'automation-scripts-that-save-me-10-hours-a-week': s9,
  'building-a-micro-saas-empire-the-portfolio-approach': s10,
  'building-a-personal-brand-on-linkedin-as-a-developer': s11,
  'building-a-remote-first-company-from-day-one': s12,
  'building-ai-products-without-a-phd-a-pragmatic-guide': s13,
  'building-in-public-a-strategy-not-a-stunt': s14,
  'claude-3-7-vs-gpt-4o-which-one-actually-writes-better-code': s15,
  'cold-email-that-gets-replies-templates-and-psychology': s16,
  'community-led-growth-the-playbook-for-2026': s17,
  'content-clusters-the-strategy-that-doubled-our-organic-traff': s18,
  'content-refresh-how-to-update-old-posts-for-new-rankings': s19,
  'context-switching-is-killing-your-output-here-is-the-fix': s20,
  'cursor-editor-10-features-that-will-change-how-you-code': s21,
  'database-design-for-indie-devs-start-simple-scale-later': s22,
  'dealing-with-imposter-syndrome-as-a-solo-founder': s23,
  'deep-work-in-the-age-of-ai-is-focus-still-possible': s24,
  'digital-minimalism-for-developers-a-30-day-challenge': s25,
  'edge-computing-when-to-use-it-when-to-skip-it': s26,
  'email-marketing-for-saas-beyond-the-welcome-sequence': s27,
  'energy-management-vs-time-management': s28,
  'from-employee-to-founder-the-mental-shift': s29,
  'from-side-project-to-50k-arr-a-12-month-timeline': s30,
  'growth-tools-2026': s31,
  'how-to-build-an-ai-saas-in-48-hours-step-by-step': s32,
  'how-to-create-a-viral-tool-that-markets-your-product': s33,
  'how-to-evaluate-ai-tools-a-framework-for-teams': s34,
  'how-to-get-your-first-1000-users-without-paid-ads': s35,
  'how-to-hire-your-first-contractor-without-losing-money': s36,
  'how-to-read-faster-without-losing-comprehension': s37,
  'how-to-run-effective-1-1s-even-if-you-hate-meetings': s38,
  'how-to-say-no-without-burning-bridges': s39,
  'how-to-validate-your-saas-idea-in-one-weekend': s40,
  'how-to-write-copy-that-sells-even-if-you-are-not-a-writer': s41,
  'how-we-use-ai-to-cut-our-content-production-time-by-70': s42,
  'keyword-research-in-2026-beyond-search-volume': s43,
  'kimi-k2-6-open-source-coding-model-explained': s44,
  'kimi-k2-open-agentic-intelligence-explained': s45,
  'kimi-k2-thinking-the-reasoning-model-explained': s46,
  'kol-marketing': s47,
  'launching-on-product-hunt-what-worked-in-2026': s48,
  'link-building-for-boring-b2b-products': s49,
  'local-seo-for-saas-does-it-even-matter': s50,
  'measuring-content-roi-metrics-that-matter-to-your-ceo': s51,
  'midjourney-v7-review-the-good-the-bad-and-the-weird': s52,
  'monorepos-in-2026-turborepo-nx-or-just-pnpm': s53,
  'no-code-mvp': s54,
  'open-source-ai-models-that-rival-gpt-4-in-2026': s55,
  'prompt-engineering-is-dead-long-live-prompt-engineering': s56,
  'react-server-components-a-practical-guide': s57,
  'reddit-marketing': s58,
  'referral-loops-how-dropbox-notion-and-linear-grew': s59,
  'remote-work-burnout-signs-prevention-recovery': s60,
  'running-llms-locally-a-complete-setup-guide-for-2026': s61,
  'saas-pricing-strategies-that-actually-convert-in-2026': s62,
  'schema-markup-that-actually-moves-the-needle': s63,
  'seo-2026-trends': s64,
  'seo-for-saas-the-long-tail-strategy-that-works': s65,
  'solo-founding-one-year-of-lessons-and-regrets': s66,
  'technical-seo-for-single-page-applications': s67,
  'testing-strategies-for-small-teams': s68,
  'the-4-hour-workweek-for-developers-reality-check': s69,
  'the-5-minute-rule-for-starting-hard-tasks': s70,
  'the-art-of-the-soft-launch-why-big-bangs-fail': s71,
  'the-best-ai-tools-for-indie-developers-in-2026': s72,
  'the-best-note-taking-apps-for-developers-in-2026': s73,
  'the-bootstrapper-s-guide-to-raising-zero-dollars': s74,
  'the-complete-guide-to-affiliate-marketing-for-saas': s75,
  'the-complete-guide-to-ai-powered-customer-support': s76,
  'the-dark-side-of-growth-hacking-what-not-to-do': s77,
  'the-developer-s-second-brain-how-i-organize-everything': s78,
  'the-emotional-rollercoaster-of-running-a-startup': s79,
  'the-exit-strategy-when-to-sell-pivot-or-shut-down': s80,
  'the-future-of-search-what-happens-when-ai-answers-everything': s81,
  'the-hidden-costs-of-ai-writing-tools-nobody-talks-about': s82,
  'the-legal-and-tax-basics-every-indie-dev-ignores': s83,
  'the-minimum-viable-marketing-stack-for-indie-devs': s84,
  'the-morning-routine-that-actually-works-for-night-owls': s85,
  'the-problem-with-productivity-porn': s86,
  'the-rise-of-ai-agents-hype-vs-reality': s87,
  'the-rise-of-local-first-apps-sync-without-the-cloud': s88,
  'the-state-of-css-in-2026-tailwind-panda-and-beyond': s89,
  'the-state-of-indie-hacker-marketing-in-2026': s90,
  'the-tech-stack-that-scales-from-0-to-1m-arr': s91,
  'time-blocking-for-creatives-a-realistic-guide': s92,
  'twitter-growth': s93,
  'video-seo-how-to-rank-on-youtube-and-google': s94,
  'web-performance-in-2026-core-web-vitals-and-beyond': s95,
  'why-i-stopped-chasing-vc-and-started-building-for-profit': s96,
  'why-i-switched-from-chatgpt-to-perplexity-for-research': s97,
  'why-most-side-projects-never-become-businesses': s98,
  'why-your-ai-generated-content-sounds-generic-and-how-to-fix-': s99,
  'why-your-ai-generated-content-sounds-generic-and-how-to-fix-it': s100,
  'why-your-landing-page-is-not-converting-and-how-to-fix-it': s101,
  'worldvqa-atomic-world-knowledge-benchmark-explained': s102,
};
