// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file aihues/catalog/v1/service.proto (package aihues.catalog.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Game, ItemCategory, Tool } from "./types_pb";
import { file_aihues_catalog_v1_types } from "./types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file aihues/catalog/v1/service.proto.
 */
export const file_aihues_catalog_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch9haWh1ZXMvY2F0YWxvZy92MS9zZXJ2aWNlLnByb3RvEhFhaWh1ZXMuY2F0YWxvZy52MSJ3ChBMaXN0VG9vbHNSZXF1ZXN0EgkKAXEYASABKAkSEQoJcGFnZV9zaXplGAIgASgFEhIKCnBhZ2VfdG9rZW4YAyABKAkSMQoIY2F0ZWdvcnkYBCABKA4yHy5haWh1ZXMuY2F0YWxvZy52MS5JdGVtQ2F0ZWdvcnkiVAoRTGlzdFRvb2xzUmVzcG9uc2USJgoFdG9vbHMYASADKAsyFy5haWh1ZXMuY2F0YWxvZy52MS5Ub29sEhcKD25leHRfcGFnZV90b2tlbhgCIAEoCSI5ChBMaXN0R2FtZXNSZXF1ZXN0EhEKCXBhZ2Vfc2l6ZRgBIAEoBRISCgpwYWdlX3Rva2VuGAIgASgJIlQKEUxpc3RHYW1lc1Jlc3BvbnNlEiYKBWdhbWVzGAEgAygLMhcuYWlodWVzLmNhdGFsb2cudjEuR2FtZRIXCg9uZXh0X3BhZ2VfdG9rZW4YAiABKAkywAEKDkNhdGFsb2dTZXJ2aWNlElYKCUxpc3RUb29scxIjLmFpaHVlcy5jYXRhbG9nLnYxLkxpc3RUb29sc1JlcXVlc3QaJC5haWh1ZXMuY2F0YWxvZy52MS5MaXN0VG9vbHNSZXNwb25zZRJWCglMaXN0R2FtZXMSIy5haWh1ZXMuY2F0YWxvZy52MS5MaXN0R2FtZXNSZXF1ZXN0GiQuYWlodWVzLmNhdGFsb2cudjEuTGlzdEdhbWVzUmVzcG9uc2VCSlpIZ2l0aHViLmNvbS9haWh1ZXMvYWl1c2h0aGEvcGFja2FnZXMvcHJvdG8tZ28vYWlodWVzL2NhdGFsb2cvdjE7Y2F0YWxvZ3YxYgZwcm90bzM", [file_aihues_catalog_v1_types]);

/**
 * @generated from message aihues.catalog.v1.ListToolsRequest
 */
export type ListToolsRequest = Message<"aihues.catalog.v1.ListToolsRequest"> & {
  /**
   * optional keyword（匹配 name/description）
   *
   * @generated from field: string q = 1;
   */
  q: string;

  /**
   * 每页数据量；默认 10，最大 20
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * 分页 token；第一页不传，后续传上一页返回的 next_page_token
   *
   * @generated from field: string page_token = 3;
   */
  pageToken: string;

  /**
   * 不传或 ITEM_CATEGORY_UNSPECIFIED 表示不过滤
   *
   * @generated from field: aihues.catalog.v1.ItemCategory category = 4;
   */
  category: ItemCategory;
};

/**
 * Describes the message aihues.catalog.v1.ListToolsRequest.
 * Use `create(ListToolsRequestSchema)` to create a new message.
 */
export const ListToolsRequestSchema: GenMessage<ListToolsRequest> = /*@__PURE__*/
  messageDesc(file_aihues_catalog_v1_service, 0);

/**
 * @generated from message aihues.catalog.v1.ListToolsResponse
 */
export type ListToolsResponse = Message<"aihues.catalog.v1.ListToolsResponse"> & {
  /**
   * @generated from field: repeated aihues.catalog.v1.Tool tools = 1;
   */
  tools: Tool[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message aihues.catalog.v1.ListToolsResponse.
 * Use `create(ListToolsResponseSchema)` to create a new message.
 */
export const ListToolsResponseSchema: GenMessage<ListToolsResponse> = /*@__PURE__*/
  messageDesc(file_aihues_catalog_v1_service, 1);

/**
 * @generated from message aihues.catalog.v1.ListGamesRequest
 */
export type ListGamesRequest = Message<"aihues.catalog.v1.ListGamesRequest"> & {
  /**
   * 每页数据量；默认 10，最大 20
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * 分页 token；第一页不传，后续传上一页返回的 next_page_token
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message aihues.catalog.v1.ListGamesRequest.
 * Use `create(ListGamesRequestSchema)` to create a new message.
 */
export const ListGamesRequestSchema: GenMessage<ListGamesRequest> = /*@__PURE__*/
  messageDesc(file_aihues_catalog_v1_service, 2);

/**
 * @generated from message aihues.catalog.v1.ListGamesResponse
 */
export type ListGamesResponse = Message<"aihues.catalog.v1.ListGamesResponse"> & {
  /**
   * @generated from field: repeated aihues.catalog.v1.Game games = 1;
   */
  games: Game[];

  /**
   * @generated from field: string next_page_token = 2;
   */
  nextPageToken: string;
};

/**
 * Describes the message aihues.catalog.v1.ListGamesResponse.
 * Use `create(ListGamesResponseSchema)` to create a new message.
 */
export const ListGamesResponseSchema: GenMessage<ListGamesResponse> = /*@__PURE__*/
  messageDesc(file_aihues_catalog_v1_service, 3);

/**
 * 公开读服务
 *
 * @generated from service aihues.catalog.v1.CatalogService
 */
export const CatalogService: GenService<{
  /**
   * @generated from rpc aihues.catalog.v1.CatalogService.ListTools
   */
  listTools: {
    methodKind: "unary";
    input: typeof ListToolsRequestSchema;
    output: typeof ListToolsResponseSchema;
  },
  /**
   * @generated from rpc aihues.catalog.v1.CatalogService.ListGames
   */
  listGames: {
    methodKind: "unary";
    input: typeof ListGamesRequestSchema;
    output: typeof ListGamesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_aihues_catalog_v1_service, 0);

