// @generated by protoc-gen-es v2.5.0 with parameter "target=ts"
// @generated from file aihues/catalog/v1/types.proto (package aihues.catalog.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file aihues/catalog/v1/types.proto.
 */
export const file_aihues_catalog_v1_types: GenFile = /*@__PURE__*/
  fileDesc("Ch1haWh1ZXMvY2F0YWxvZy92MS90eXBlcy5wcm90bxIRYWlodWVzLmNhdGFsb2cudjEiqQIKBFRvb2wSCgoCaWQYASABKAkSDAoEc2x1ZxgCIAEoCRIMCgRpY29uGAMgASgJEgwKBG5hbWUYBCABKAkSEwoLZGVzY3JpcHRpb24YBSABKAkSMQoIY2F0ZWdvcnkYBiABKA4yHy5haWh1ZXMuY2F0YWxvZy52MS5JdGVtQ2F0ZWdvcnkSLQoGc3RhdHVzGAcgASgOMh0uYWlodWVzLmNhdGFsb2cudjEuSXRlbVN0YXR1cxISCgpzb3J0X29yZGVyGAggASgFEi8KC2NyZWF0ZV90aW1lGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgt1cGRhdGVfdGltZRgKIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAi9gEKBEdhbWUSCgoCaWQYASABKAkSDAoEc2x1ZxgCIAEoCRIMCgRpY29uGAMgASgJEgwKBG5hbWUYBCABKAkSEwoLZGVzY3JpcHRpb24YBSABKAkSLQoGc3RhdHVzGAYgASgOMh0uYWlodWVzLmNhdGFsb2cudjEuSXRlbVN0YXR1cxISCgpzb3J0X29yZGVyGAcgASgFEi8KC2NyZWF0ZV90aW1lGAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIvCgt1cGRhdGVfdGltZRgJIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAqTQoISXRlbUtpbmQSGQoVSVRFTV9LSU5EX1VOU1BFQ0lGSUVEEAASEgoOSVRFTV9LSU5EX1RPT0wQARISCg5JVEVNX0tJTkRfR0FNRRACKnUKCkl0ZW1TdGF0dXMSGwoXSVRFTV9TVEFUVVNfVU5TUEVDSUZJRUQQABIVChFJVEVNX1NUQVRVU19EUkFGVBABEhkKFUlURU1fU1RBVFVTX1BVQkxJU0hFRBACEhgKFElURU1fU1RBVFVTX0FSQ0hJVkVEEAMqgwEKDEl0ZW1DYXRlZ29yeRIdChlJVEVNX0NBVEVHT1JZX1VOU1BFQ0lGSUVEEAASGwoXSVRFTV9DQVRFR09SWV9ERVZFTE9QRVIQARIZChVJVEVNX0NBVEVHT1JZX1VUSUxJVFkQAhIcChhJVEVNX0NBVEVHT1JZX0FJX1dSSVRJTkcQA0JKWkhnaXRodWIuY29tL2FpaHVlcy9haXVzaHRoYS9wYWNrYWdlcy9wcm90by1nby9haWh1ZXMvY2F0YWxvZy92MTtjYXRhbG9ndjFiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * 工具元数据
 *
 * @generated from message aihues.catalog.v1.Tool
 */
export type Tool = Message<"aihues.catalog.v1.Tool"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: aihues.catalog.v1.ItemCategory category = 6;
   */
  category: ItemCategory;

  /**
   * @generated from field: aihues.catalog.v1.ItemStatus status = 7;
   */
  status: ItemStatus;

  /**
   * @generated from field: int32 sort_order = 8;
   */
  sortOrder: number;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 9;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 10;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message aihues.catalog.v1.Tool.
 * Use `create(ToolSchema)` to create a new message.
 */
export const ToolSchema: GenMessage<Tool> = /*@__PURE__*/
  messageDesc(file_aihues_catalog_v1_types, 0);

/**
 * 游戏元数据
 *
 * @generated from message aihues.catalog.v1.Game
 */
export type Game = Message<"aihues.catalog.v1.Game"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * @generated from field: string icon = 3;
   */
  icon: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: aihues.catalog.v1.ItemStatus status = 6;
   */
  status: ItemStatus;

  /**
   * @generated from field: int32 sort_order = 7;
   */
  sortOrder: number;

  /**
   * @generated from field: google.protobuf.Timestamp create_time = 8;
   */
  createTime?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp update_time = 9;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message aihues.catalog.v1.Game.
 * Use `create(GameSchema)` to create a new message.
 */
export const GameSchema: GenMessage<Game> = /*@__PURE__*/
  messageDesc(file_aihues_catalog_v1_types, 1);

/**
 * 条目类型（多态目录表的行类型判别符；仅用于内部存储，不暴露在 Tool / Game 消息上）
 *
 * @generated from enum aihues.catalog.v1.ItemKind
 */
export enum ItemKind {
  /**
   * @generated from enum value: ITEM_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ITEM_KIND_TOOL = 1;
   */
  TOOL = 1,

  /**
   * @generated from enum value: ITEM_KIND_GAME = 2;
   */
  GAME = 2,
}

/**
 * Describes the enum aihues.catalog.v1.ItemKind.
 */
export const ItemKindSchema: GenEnum<ItemKind> = /*@__PURE__*/
  enumDesc(file_aihues_catalog_v1_types, 0);

/**
 * 条目状态
 *
 * @generated from enum aihues.catalog.v1.ItemStatus
 */
export enum ItemStatus {
  /**
   * @generated from enum value: ITEM_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ITEM_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: ITEM_STATUS_PUBLISHED = 2;
   */
  PUBLISHED = 2,

  /**
   * @generated from enum value: ITEM_STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,
}

/**
 * Describes the enum aihues.catalog.v1.ItemStatus.
 */
export const ItemStatusSchema: GenEnum<ItemStatus> = /*@__PURE__*/
  enumDesc(file_aihues_catalog_v1_types, 1);

/**
 * 条目分类（tool / game 通用；目前枚举值仅覆盖 tool，未来 game 分类可在此扩展）
 *
 * @generated from enum aihues.catalog.v1.ItemCategory
 */
export enum ItemCategory {
  /**
   * @generated from enum value: ITEM_CATEGORY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ITEM_CATEGORY_DEVELOPER = 1;
   */
  DEVELOPER = 1,

  /**
   * @generated from enum value: ITEM_CATEGORY_UTILITY = 2;
   */
  UTILITY = 2,

  /**
   * @generated from enum value: ITEM_CATEGORY_AI_WRITING = 3;
   */
  AI_WRITING = 3,
}

/**
 * Describes the enum aihues.catalog.v1.ItemCategory.
 */
export const ItemCategorySchema: GenEnum<ItemCategory> = /*@__PURE__*/
  enumDesc(file_aihues_catalog_v1_types, 2);

