# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: '../cache/schemas/tasks.json'

tasks:
  container:
    command: docker build -f Dockerfile --push -t $CI_REGISTRY/papers-web:${CI_COMMIT_SHORT_SHA:0:7} .
    inputs:
      - 'Dockerfile'
      - 'package.json'
      - 'src/**/*'
    options:
      runInCI: true
