# yaml-language-server: $schema=../cache/schemas/tasks.json
$schema: '../cache/schemas/tasks.json'

fileGroups:
  app:
    - 'app/**/*'

tasks:
  lint:
    command: pnpm run lint
    inputs:
      - '@group(app)'
      - 'eslint.config.*'

  dev:
    command: pnpm run dev
    local: true

  build:
    command: pnpm run build
    inputs:
      - '@group(app)'
      - 'next.config.*'
      - 'tsconfig.json'
      - 'tailwind.config.*'
      - 'postcss.config.*'
    outputs:
      - '.next'

  start:
    command: pnpm run start
    deps:
      - build
    local: true

  test:
    command: pnpm run test
    inputs:
      - '@group(app)'
      - 'vitest.config.*'
      - 'vitest.setup.*'
    options:
      outputStyle: 'buffer-only-failure'

  typecheck:
    command: tsc --noEmit
    inputs:
      - '@group(app)'
      - 'tsconfig.json'
