// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: aihues/catalog/v1/service.proto

package catalogv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/aihues/aiushtha/packages/proto-go/aihues/catalog/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CatalogServiceName is the fully-qualified name of the CatalogService service.
	CatalogServiceName = "aihues.catalog.v1.CatalogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CatalogServiceListToolsProcedure is the fully-qualified name of the CatalogService's ListTools
	// RPC.
	CatalogServiceListToolsProcedure = "/aihues.catalog.v1.CatalogService/ListTools"
	// CatalogServiceListGamesProcedure is the fully-qualified name of the CatalogService's ListGames
	// RPC.
	CatalogServiceListGamesProcedure = "/aihues.catalog.v1.CatalogService/ListGames"
	// CatalogServiceSearchCatalogProcedure is the fully-qualified name of the CatalogService's
	// SearchCatalog RPC.
	CatalogServiceSearchCatalogProcedure = "/aihues.catalog.v1.CatalogService/SearchCatalog"
	// CatalogServiceRelatedItemsProcedure is the fully-qualified name of the CatalogService's
	// RelatedItems RPC.
	CatalogServiceRelatedItemsProcedure = "/aihues.catalog.v1.CatalogService/RelatedItems"
)

// CatalogServiceClient is a client for the aihues.catalog.v1.CatalogService service.
type CatalogServiceClient interface {
	ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error)
	ListGames(context.Context, *connect.Request[v1.ListGamesRequest]) (*connect.Response[v1.ListGamesResponse], error)
	// 语义搜索（全站工具/游戏/测试），由 FAISS + 句向量驱动
	SearchCatalog(context.Context, *connect.Request[v1.SearchCatalogRequest]) (*connect.Response[v1.SearchCatalogResponse], error)
	// 相关推荐（按 slug 或自由文本，限定同类型）
	RelatedItems(context.Context, *connect.Request[v1.RelatedItemsRequest]) (*connect.Response[v1.RelatedItemsResponse], error)
}

// NewCatalogServiceClient constructs a client for the aihues.catalog.v1.CatalogService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCatalogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CatalogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	catalogServiceMethods := v1.File_aihues_catalog_v1_service_proto.Services().ByName("CatalogService").Methods()
	return &catalogServiceClient{
		listTools: connect.NewClient[v1.ListToolsRequest, v1.ListToolsResponse](
			httpClient,
			baseURL+CatalogServiceListToolsProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("ListTools")),
			connect.WithClientOptions(opts...),
		),
		listGames: connect.NewClient[v1.ListGamesRequest, v1.ListGamesResponse](
			httpClient,
			baseURL+CatalogServiceListGamesProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("ListGames")),
			connect.WithClientOptions(opts...),
		),
		searchCatalog: connect.NewClient[v1.SearchCatalogRequest, v1.SearchCatalogResponse](
			httpClient,
			baseURL+CatalogServiceSearchCatalogProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("SearchCatalog")),
			connect.WithClientOptions(opts...),
		),
		relatedItems: connect.NewClient[v1.RelatedItemsRequest, v1.RelatedItemsResponse](
			httpClient,
			baseURL+CatalogServiceRelatedItemsProcedure,
			connect.WithSchema(catalogServiceMethods.ByName("RelatedItems")),
			connect.WithClientOptions(opts...),
		),
	}
}

// catalogServiceClient implements CatalogServiceClient.
type catalogServiceClient struct {
	listTools     *connect.Client[v1.ListToolsRequest, v1.ListToolsResponse]
	listGames     *connect.Client[v1.ListGamesRequest, v1.ListGamesResponse]
	searchCatalog *connect.Client[v1.SearchCatalogRequest, v1.SearchCatalogResponse]
	relatedItems  *connect.Client[v1.RelatedItemsRequest, v1.RelatedItemsResponse]
}

// ListTools calls aihues.catalog.v1.CatalogService.ListTools.
func (c *catalogServiceClient) ListTools(ctx context.Context, req *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error) {
	return c.listTools.CallUnary(ctx, req)
}

// ListGames calls aihues.catalog.v1.CatalogService.ListGames.
func (c *catalogServiceClient) ListGames(ctx context.Context, req *connect.Request[v1.ListGamesRequest]) (*connect.Response[v1.ListGamesResponse], error) {
	return c.listGames.CallUnary(ctx, req)
}

// SearchCatalog calls aihues.catalog.v1.CatalogService.SearchCatalog.
func (c *catalogServiceClient) SearchCatalog(ctx context.Context, req *connect.Request[v1.SearchCatalogRequest]) (*connect.Response[v1.SearchCatalogResponse], error) {
	return c.searchCatalog.CallUnary(ctx, req)
}

// RelatedItems calls aihues.catalog.v1.CatalogService.RelatedItems.
func (c *catalogServiceClient) RelatedItems(ctx context.Context, req *connect.Request[v1.RelatedItemsRequest]) (*connect.Response[v1.RelatedItemsResponse], error) {
	return c.relatedItems.CallUnary(ctx, req)
}

// CatalogServiceHandler is an implementation of the aihues.catalog.v1.CatalogService service.
type CatalogServiceHandler interface {
	ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error)
	ListGames(context.Context, *connect.Request[v1.ListGamesRequest]) (*connect.Response[v1.ListGamesResponse], error)
	// 语义搜索（全站工具/游戏/测试），由 FAISS + 句向量驱动
	SearchCatalog(context.Context, *connect.Request[v1.SearchCatalogRequest]) (*connect.Response[v1.SearchCatalogResponse], error)
	// 相关推荐（按 slug 或自由文本，限定同类型）
	RelatedItems(context.Context, *connect.Request[v1.RelatedItemsRequest]) (*connect.Response[v1.RelatedItemsResponse], error)
}

// NewCatalogServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCatalogServiceHandler(svc CatalogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	catalogServiceMethods := v1.File_aihues_catalog_v1_service_proto.Services().ByName("CatalogService").Methods()
	catalogServiceListToolsHandler := connect.NewUnaryHandler(
		CatalogServiceListToolsProcedure,
		svc.ListTools,
		connect.WithSchema(catalogServiceMethods.ByName("ListTools")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceListGamesHandler := connect.NewUnaryHandler(
		CatalogServiceListGamesProcedure,
		svc.ListGames,
		connect.WithSchema(catalogServiceMethods.ByName("ListGames")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceSearchCatalogHandler := connect.NewUnaryHandler(
		CatalogServiceSearchCatalogProcedure,
		svc.SearchCatalog,
		connect.WithSchema(catalogServiceMethods.ByName("SearchCatalog")),
		connect.WithHandlerOptions(opts...),
	)
	catalogServiceRelatedItemsHandler := connect.NewUnaryHandler(
		CatalogServiceRelatedItemsProcedure,
		svc.RelatedItems,
		connect.WithSchema(catalogServiceMethods.ByName("RelatedItems")),
		connect.WithHandlerOptions(opts...),
	)
	return "/aihues.catalog.v1.CatalogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CatalogServiceListToolsProcedure:
			catalogServiceListToolsHandler.ServeHTTP(w, r)
		case CatalogServiceListGamesProcedure:
			catalogServiceListGamesHandler.ServeHTTP(w, r)
		case CatalogServiceSearchCatalogProcedure:
			catalogServiceSearchCatalogHandler.ServeHTTP(w, r)
		case CatalogServiceRelatedItemsProcedure:
			catalogServiceRelatedItemsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCatalogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCatalogServiceHandler struct{}

func (UnimplementedCatalogServiceHandler) ListTools(context.Context, *connect.Request[v1.ListToolsRequest]) (*connect.Response[v1.ListToolsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aihues.catalog.v1.CatalogService.ListTools is not implemented"))
}

func (UnimplementedCatalogServiceHandler) ListGames(context.Context, *connect.Request[v1.ListGamesRequest]) (*connect.Response[v1.ListGamesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aihues.catalog.v1.CatalogService.ListGames is not implemented"))
}

func (UnimplementedCatalogServiceHandler) SearchCatalog(context.Context, *connect.Request[v1.SearchCatalogRequest]) (*connect.Response[v1.SearchCatalogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aihues.catalog.v1.CatalogService.SearchCatalog is not implemented"))
}

func (UnimplementedCatalogServiceHandler) RelatedItems(context.Context, *connect.Request[v1.RelatedItemsRequest]) (*connect.Response[v1.RelatedItemsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("aihues.catalog.v1.CatalogService.RelatedItems is not implemented"))
}
